import { prisma } from "@/lib/prisma";
import { requirePlatformPermission } from "@/lib/platform";
import { createAnnouncementAction, createInternalNoteAction, createPlatformTaskAction, updatePlatformTaskStatusAction } from "./actions";

export default async function OperationsPage() {
  await requirePlatformPermission("support.manage");
  const [clinics, tasks, notes, tickets, announcements] = await Promise.all([prisma.clinic.findMany({ select: { id: true, name: true, brandName: true }, orderBy: { name: "asc" } }), prisma.platformTask.findMany({ include: { clinic: { select: { name: true, brandName: true } } }, orderBy: [{ status: "asc" }, { dueAt: "asc" }], take: 100 }), prisma.platformInternalNote.findMany({ include: { clinic: { select: { name: true, brandName: true } } }, orderBy: { createdAt: "desc" }, take: 50 }), prisma.platformSupportTicket.findMany({ orderBy: { updatedAt: "desc" }, take: 50 }), prisma.platformAnnouncement.findMany({ orderBy: { createdAt: "desc" }, take: 30 })]);
  return <main className="space-y-6 pb-12"><header><p className="platform-eyebrow">Operations</p><h1 className="mt-1 text-3xl font-bold">Internal operations</h1><p className="mt-2 text-sm text-text-muted">Notes and tasks are platform-only records; announcements are authored here but are not yet delivered into clinic SaaS.</p></header>
    <section className="space-y-6"><Panel title="Create internal note"><form action={createInternalNoteAction} className="grid gap-3"><select required name="clinicId" className="h-10 rounded border px-3"><option value="">Select clinic</option>{clinics.map((c) => <option key={c.id} value={c.id}>{c.brandName || c.name}</option>)}</select><select name="category" className="h-10 rounded border px-3"><option>GENERAL</option><option>ONBOARDING</option><option>BILLING</option><option>WHATSAPP</option><option>SUPPORT</option></select><textarea required name="body" className="min-h-24 rounded border p-3" placeholder="Internal-only note"/><button className="w-fit rounded bg-primary px-4 py-2 text-sm font-semibold text-white">Save note</button></form></Panel><Panel title="Create task"><form action={createPlatformTaskAction} className="grid gap-3"><input required name="title" className="h-10 rounded border px-3" placeholder="Task title"/><select name="clinicId" className="h-10 rounded border px-3"><option value="">Platform-wide</option>{clinics.map((c) => <option key={c.id} value={c.id}>{c.brandName || c.name}</option>)}</select><select name="priority" className="h-10 rounded border px-3"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select><textarea name="description" className="min-h-20 rounded border p-3" placeholder="Optional context"/><input name="dueAt" type="date" className="h-10 rounded border px-3"/><button className="w-fit rounded bg-primary px-4 py-2 text-sm font-semibold text-white">Create task</button></form></Panel></section>
    <Panel title="Operational queue"><div className="divide-y">{tasks.map((task) => <div key={task.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-semibold">{task.title}</p><p className="text-xs text-text-muted">{task.clinic?.brandName || task.clinic?.name || "Platform-wide"} · {task.priority} · due {task.dueAt?.toLocaleDateString("en-IN") || "not set"}</p></div><form action={updatePlatformTaskStatusAction} className="flex gap-2"><input type="hidden" name="id" value={task.id}/><select name="status" defaultValue={task.status} className="h-9 rounded border px-2">{["OPEN", "IN_PROGRESS", "BLOCKED", "DONE"].map((s) => <option key={s}>{s}</option>)}</select><button className="rounded border px-3 text-sm">Save</button></form></div>)}{!tasks.length && <Empty text="No internal tasks."/>}</div></Panel>
    <section className="space-y-6"><Panel title="Recent internal notes"><div className="divide-y">{notes.map((note) => <div key={note.id} className="py-3"><p className="text-sm font-semibold">{note.clinic.brandName || note.clinic.name} · {note.category}</p><p className="mt-1 text-sm text-text-muted">{note.body}</p></div>)}{!notes.length && <Empty text="No internal notes."/>}</div></Panel><Panel title="Support cases"><div className="divide-y">{tickets.map((ticket) => <div key={ticket.id} className="py-3 text-sm"><p className="font-semibold">#{ticket.id} · {ticket.subject}</p><p className="text-xs text-text-muted">{ticket.status} · {ticket.priority} · clinic {ticket.clinicId || "platform"}</p></div>)}{!tickets.length && <Empty text="No support cases."/>}</div></Panel></section>
    <Panel title="Announcements"><form action={createAnnouncementAction} className="grid gap-3 md:grid-cols-2"><input required name="title" className="h-10 rounded border px-3" placeholder="Title"/><select name="targetType" className="h-10 rounded border px-3"><option value="ALL_CLINICS">All clinics</option><option value="CLINIC">Specific clinic</option></select><select name="targetClinicId" className="h-10 rounded border px-3"><option value="">Choose only for specific clinic</option>{clinics.map((c) => <option key={c.id} value={c.id}>{c.brandName || c.name}</option>)}</select><select name="severity" className="h-10 rounded border px-3"><option>INFO</option><option>WARNING</option><option>CRITICAL</option></select><textarea required name="message" className="min-h-20 rounded border p-3 md:col-span-2" placeholder="Announcement message"/><button className="w-fit rounded bg-primary px-4 py-2 text-sm font-semibold text-white">Save announcement</button></form><div className="mt-5 divide-y">{announcements.map((a) => <div key={a.id} className="py-3 text-sm"><p className="font-semibold">{a.severity} · {a.title}</p><p className="text-xs text-text-muted">{a.targetType}{a.targetClinicId ? ` #${a.targetClinicId}` : ""} · created {a.createdAt.toLocaleDateString("en-IN")}</p></div>)}{!announcements.length && <Empty text="No announcements authored."/>}</div></Panel>
  </main>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-card p-5"><h2 className="font-bold">{title}</h2><div className="mt-3">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <p className="py-3 text-sm text-text-muted">{text}</p>; }
