export const dynamic = "force-dynamic";

import { AlertTriangle, CheckCircle2, Clock3, FlaskConical, Plus, RotateCcw, Send } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import PendingSubmitButton from "@/components/dashboard/PendingSubmitButton";
import { WhatsAppQuickSend } from "@/components/whatsapp/WhatsAppQuickSend";
import { createLabCaseAction, createReworkAction, updateLabStatusAction } from "./actions";

const statuses = ["SENT_TO_LAB", "IN_PROGRESS", "WAX_STAGE", "METAL_STAGE", "CERAMIC_STAGE", "READY", "DELIVERED", "COMPLETED", "REWORK", "CANCELLED"];
const tone: Record<string, string> = { SENT_TO_LAB:"bg-sky-100 text-sky-800", IN_PROGRESS:"bg-amber-100 text-amber-800", WAX_STAGE:"bg-orange-100 text-orange-800", METAL_STAGE:"bg-slate-200 text-slate-800", CERAMIC_STAGE:"bg-fuchsia-100 text-fuchsia-800", READY:"bg-emerald-100 text-emerald-800", DELIVERED:"bg-violet-100 text-violet-800", COMPLETED:"bg-teal-100 text-teal-800", REWORK:"bg-rose-100 text-rose-800", CANCELLED:"bg-slate-100 text-slate-600" };

export default async function LaboratoryPage() {
  const user = await requireUser(); const today = new Date(); today.setHours(0,0,0,0);
  const [cases, patients, events] = await Promise.all([
    prisma.labCase.findMany({ where:{ clinicId:user.clinicId }, include:{ patient:{ select:{ fullName:true, phone:true } }, events:{ orderBy:{ createdAt:"desc" }, take:1 }, reworks:{ select:{ id:true } } }, orderBy:[{ dueDate:"asc" },{ updatedAt:"desc" }], take:100 }),
    prisma.patient.findMany({ where:{ clinicId:user.clinicId }, select:{ id:true, fullName:true, phone:true }, orderBy:{ fullName:"asc" }, take:200 }),
    prisma.labCaseEvent.findMany({ where:{ clinicId:user.clinicId }, include:{ labCase:{ select:{ orderNumber:true, patient:{ select:{ fullName:true } } } } }, orderBy:{ createdAt:"desc" }, take:6 }),
  ]);
  const open = cases.filter(x=>!['DELIVERED','COMPLETED','CANCELLED'].includes(x.status)); const delayed = open.filter(x=>x.dueDate && x.dueDate < today); const ready = cases.filter(x=>x.status==='READY'); const reworks = cases.filter(x=>x.status==='REWORK');
  const metrics = [["Total orders",cases.length,FlaskConical,"text-indigo-600"],["Pending",open.length,Clock3,"text-amber-600"],["Ready for delivery",ready.length,CheckCircle2,"text-emerald-600"],["Delayed",delayed.length,AlertTriangle,"text-rose-600"],["Rework cases",reworks.length,RotateCcw,"text-orange-600"]] as const;
  return <div className="dashboard-list-page mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-primary">Laboratory command centre</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Laboratory management</h1><p className="mt-2 text-muted-foreground">Live case tracking, prescription details, delivery follow-ups and permanent rework history.</p></div><span className="rounded-full bg-sky-50 px-3 py-1.5 text-sm font-bold text-sky-700">{events.length} recent timeline updates</span></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label,value,Icon,color])=><article key={label} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><Icon className={`size-6 ${color}`}/></div></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-2"><Plus className="size-5 text-primary"/><h2 className="text-lg font-bold">New laboratory order</h2></div><form action={createLabCaseAction} className="mt-5 grid gap-3 sm:grid-cols-2"><select required name="patientId" className="h-11 rounded-xl border bg-card px-3"><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.fullName} — {p.phone}</option>)}</select><select name="caseType" required className="h-11 rounded-xl border bg-card px-3"><option value="">Case type</option>{["Crown","Bridge","Veneer","Denture","Implant","Aligner","Zirconia","PFM","E-max","Temporary Crown","Wax Try-in","Metal Try-in","Custom"].map(x=><option key={x}>{x}</option>)}</select><input required name="labName" placeholder="Laboratory name" className="h-11 rounded-xl border px-3"/><input name="technician" placeholder="Technician name" className="h-11 rounded-xl border px-3"/><input name="teeth" placeholder="Tooth numbers (e.g. 11, 12)" className="h-11 rounded-xl border px-3"/><input name="material" placeholder="Material / margin" className="h-11 rounded-xl border px-3"/><input name="shade" placeholder="Shade" className="h-11 rounded-xl border px-3"/><input name="dueDate" type="date" className="h-11 rounded-xl border px-3"/><select name="priority" className="h-11 rounded-xl border bg-card px-3"><option value="NORMAL">Normal priority</option><option value="URGENT">Urgent priority</option></select><input name="doctor" placeholder="Treating doctor" className="h-11 rounded-xl border px-3"/><input name="notes" placeholder="Prescription / special instructions" className="h-11 rounded-xl border px-3 sm:col-span-2"/><PendingSubmitButton label="Create order" pendingLabel="Creating..." className="h-11 rounded-xl bg-primary px-4 font-semibold text-primary-foreground sm:col-span-2"/></form></article>
    <article className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h2 className="text-lg font-bold">Today’s follow-ups</h2><div className="mt-4 space-y-3">{delayed.slice(0,5).map(c=><div key={c.id} className="rounded-xl bg-rose-50 p-3 text-sm"><p className="font-bold">{c.patient.fullName} · {c.labName}</p><p className="mt-1 text-rose-700">Delivery overdue — contact laboratory</p></div>)}{ready.slice(0,5).map(c=><div key={c.id} className="rounded-xl bg-emerald-50 p-3 text-sm"><p className="font-bold">{c.patient.fullName} · ready</p><p className="mt-1 text-emerald-700">Arrange patient trial or collection.</p></div>)}{!delayed.length&&!ready.length&&<p className="py-8 text-sm text-muted-foreground">No urgent laboratory follow-ups today.</p>}</div></article></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="flex items-center justify-between border-b px-6 py-5"><div><h2 className="text-lg font-bold">Case board</h2><p className="text-sm text-muted-foreground">Status changes create an immutable timestamped timeline.</p></div><Send className="size-5 text-primary"/></div><div className="divide-y divide-border">{cases.map(c=>{const days=c.dueDate?Math.ceil((c.dueDate.getTime()-today.getTime())/86400000):null;return <article key={c.id} className="grid gap-4 px-6 py-5 xl:grid-cols-[1.4fr_.8fr_1fr]"><div><div className="flex flex-wrap gap-2"><p className="font-bold">{c.orderNumber || `LAB-${c.id}`} · {c.caseType}</p><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${tone[c.status]}`}>{c.status.replaceAll('_',' ')}</span>{c.priority==='URGENT'&&<span className="rounded-full bg-rose-600 px-2 py-0.5 text-xs font-bold text-white">URGENT</span>}</div><p className="mt-1 text-sm text-muted-foreground">{c.patient.fullName} · {c.labName}{c.teeth?` · Teeth ${c.teeth}`:''}</p><p className="mt-1 text-xs text-muted-foreground">{c.dueDate?`${days!==null&&days<0?`${Math.abs(days)} days late`:`${days} days remaining`} · Due ${c.dueDate.toLocaleDateString('en-IN')}`:'No delivery date'} · V{c.version}</p>{c.events[0]&&<p className="mt-2 text-xs text-slate-500">Last activity: {c.events[0].type.replaceAll('_',' ')} · {c.events[0].createdAt.toLocaleString('en-IN')}</p>}</div><form action={updateLabStatusAction} className="flex gap-2"><input type="hidden" name="id" value={c.id}/><select name="status" defaultValue={c.status} className="h-10 min-w-0 rounded-xl border bg-card px-2 text-xs">{statuses.map(s=><option key={s}>{s.replaceAll('_',' ')}</option>)}</select><button className="h-10 rounded-xl border px-3 text-sm font-semibold">Update</button></form><div className="flex flex-wrap gap-2"><WhatsAppQuickSend phone={c.labWhatsapp || c.labPhone} title="Message lab"/><form action={createReworkAction} className="flex flex-wrap gap-2"><input type="hidden" name="id" value={c.id}/><input required name="reason" placeholder="Rework reason" className="h-10 min-w-0 flex-1 rounded-xl border px-3 text-sm"/><input name="dueDate" type="date" className="h-10 rounded-xl border px-2 text-xs"/><button className="h-10 rounded-xl bg-rose-50 px-3 text-sm font-bold text-rose-700">Rework</button></form></div></article>})}{!cases.length&&<p className="px-6 py-12 text-center text-sm text-muted-foreground">Create your first lab order to begin the digital register.</p>}</div></section>
  </div>;
}
