import Link from "next/link";
import { Activity, ArrowDownRight, ArrowUpRight, Building2, CalendarDays, CircleAlert, HeartPulse, MessageCircle, Minus, Users } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { hasPlatformPermission, requirePlatformPermission } from "@/lib/platform";
import { getClinicReadiness } from "@/lib/platform-readiness";
import { PlatformPageHeader, PlatformState, PlatformStatus } from "@/components/platform/PlatformPrimitives";

type Params = { range?: string; activity?: string };
const rangeDays = { today: 1, "7d": 7, "30d": 30, "90d": 90 } as const;
function startOfDay(value = new Date()) { const date = new Date(value); date.setHours(0, 0, 0, 0); return date; }
function addDays(value: Date, days: number) { const date = new Date(value); date.setDate(date.getDate() + days); return date; }
function change(current: number, previous: number) { if (!previous) return current ? 100 : 0; return Math.round(((current - previous) / previous) * 100); }
function activityMatches(action: string, filter: string) { const value = action.toUpperCase(); if (filter === "security") return /LOGIN|SESSION|PASSWORD|ACCESS|ROLE/.test(value); if (filter === "tenant") return /CLINIC|TENANT|OWNER|USER/.test(value); if (filter === "commercial") return /PAYMENT|INVOICE|SUBSCRIPTION|PLAN|BILLING/.test(value); return true; }

export default async function PlatformOverview({ searchParams }: { searchParams: Promise<Params> }) {
  const admin = await requirePlatformPermission("tenant.read");
  const canCreateTenant = hasPlatformPermission(admin, "tenant.create");
  const canViewAnalytics = hasPlatformPermission(admin, "analytics.read");
  const canViewWhatsApp = hasPlatformPermission(admin, "whatsapp.read");
  const canViewLogs = hasPlatformPermission(admin, "logs.read");
  const p = await searchParams;
  const range = p.range && p.range in rangeDays ? p.range as keyof typeof rangeDays : "30d";
  const activity = ["all", "security", "tenant", "commercial"].includes(p.activity || "") ? p.activity! : "all";
  const days = rangeDays[range];
  const currentStart = addDays(startOfDay(), -(days - 1));
  const previousStart = addDays(currentStart, -days);
  const [all, active, suspended, connected, currentClinics, previousClinics, users, patients, currentPatients, previousPatients, currentAppointments, previousAppointments, messageGroups, failedJobs, readinessInput, rawEvents, clinicDates] = await Promise.all([
    prisma.clinic.count(), prisma.clinic.count({ where: { status: "ACTIVE" } }), prisma.clinic.count({ where: { status: "SUSPENDED" } }), canViewWhatsApp ? prisma.clinicWhatsAppConnection.count({ where: { disconnectedAt: null } }) : Promise.resolve(0),
    prisma.clinic.count({ where: { createdAt: { gte: currentStart } } }), prisma.clinic.count({ where: { createdAt: { gte: previousStart, lt: currentStart } } }), canViewAnalytics ? prisma.user.count({ where: { active: true } }) : Promise.resolve(0), canViewAnalytics ? prisma.patient.count() : Promise.resolve(0),
    canViewAnalytics ? prisma.patient.count({ where: { createdAt: { gte: currentStart } } }) : Promise.resolve(0), canViewAnalytics ? prisma.patient.count({ where: { createdAt: { gte: previousStart, lt: currentStart } } }) : Promise.resolve(0),
    canViewAnalytics ? prisma.appointment.count({ where: { createdAt: { gte: currentStart }, archivedAt: null } }) : Promise.resolve(0), canViewAnalytics ? prisma.appointment.count({ where: { createdAt: { gte: previousStart, lt: currentStart }, archivedAt: null } }) : Promise.resolve(0),
    canViewWhatsApp ? prisma.whatsAppMessage.groupBy({ by: ["deliveryStatus"], where: { direction: "OUTBOUND", createdAt: { gte: currentStart } }, _count: { _all: true } }) : Promise.resolve([]),
    canViewWhatsApp ? prisma.scheduledWhatsAppMessage.count({ where: { status: { in: ["FAILED", "DEAD_LETTER"] } } }) : Promise.resolve(0),
    prisma.clinic.findMany({ select: { id: true, name: true, brandName: true, phone: true, address: true, users: { select: { active: true } }, services: { select: { active: true } }, hours: { select: { isClosed: true } }, whatsappConnection: { select: { disconnectedAt: true } } } }),
    canViewLogs ? prisma.auditLog.findMany({ take: 40, orderBy: { createdAt: "desc" }, include: { clinic: { select: { name: true, brandName: true } }, user: { select: { fullName: true } } } }) : Promise.resolve([]),
    prisma.clinic.findMany({ where: { createdAt: { gte: previousStart } }, select: { createdAt: true } }),
  ]);

  const messageCounts = new Map(messageGroups.map((item) => [item.deliveryStatus.toUpperCase(), item._count._all]));
  const queued = messageCounts.get("QUEUED") || 0; const sent = (messageCounts.get("SENT") || 0) + (messageCounts.get("DELIVERED") || 0) + (messageCounts.get("READ") || 0); const delivered = (messageCounts.get("DELIVERED") || 0) + (messageCounts.get("READ") || 0); const read = messageCounts.get("READ") || 0; const messageFailed = messageCounts.get("FAILED") || 0;
  const outbound = [...messageCounts.values()].reduce((sum, value) => sum + value, 0);
  const readiness = readinessInput.map((clinic) => ({ ...clinic, readiness: getClinicReadiness(clinic) }));
  const averageReadiness = readiness.length ? Math.round(readiness.reduce((sum, clinic) => sum + clinic.readiness.percent, 0) / readiness.length) : 100;
  const attention = readiness.filter((clinic) => clinic.readiness.percent < 100).sort((a, b) => a.readiness.percent - b.readiness.percent).slice(0, 6);
  const severity = { critical: readiness.filter((clinic) => clinic.readiness.percent < 40).length, warning: readiness.filter((clinic) => clinic.readiness.percent >= 40 && clinic.readiness.percent < 80).length, watch: readiness.filter((clinic) => clinic.readiness.percent >= 80 && clinic.readiness.percent < 100).length };
  const messagingHealth = canViewWhatsApp ? (connected / Math.max(1, all)) * 25 : 25;
  const healthScore = all ? Math.max(0, Math.round(((active / all) * 35) + messagingHealth + ((averageReadiness / 100) * 40) - (canViewWhatsApp ? Math.min(15, failedJobs * 3) : 0))) : 100;
  const events = rawEvents.filter((event) => activityMatches(event.action, activity)).slice(0, 10);
  const bucketCount = range === "today" ? 6 : range === "7d" ? 7 : range === "30d" ? 10 : 12;
  const bucketDays = Math.max(1, Math.ceil(days / bucketCount));
  const growth = Array.from({ length: bucketCount }, (_, index) => { const from = addDays(currentStart, index * bucketDays); const to = addDays(from, bucketDays); return { label: from.toLocaleDateString("en-IN", { day: "numeric", month: "short" }), value: clinicDates.filter((clinic) => clinic.createdAt >= from && clinic.createdAt < to).length }; });
  const qs = (extra: Record<string, string>) => new URLSearchParams({ range, activity, ...extra }).toString();

  return <main className="space-y-6 pb-12"><PlatformPageHeader eyebrow="Enterprise control centre" title="Portfolio overview" description="Portfolio health, growth, delivery performance, and urgent operator actions in one decision surface." actions={<>{canCreateTenant && <Link href="/platform/clinics/new" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Provision clinic</Link>}<Link href="/platform/clinics" className="rounded-lg border bg-card px-4 py-2 text-sm font-semibold">Tenant directory</Link></>}/>
    <section className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Comparisons use the immediately preceding {days}-day period.</p><form className="flex items-center gap-2"><input type="hidden" name="activity" value={activity}/><label className="text-sm font-semibold">Reporting period <select name="range" defaultValue={range} className="ml-2 rounded-lg border bg-card px-2 py-1.5"><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select></label><button className="rounded-lg border bg-card px-3 py-1.5 text-sm font-semibold">Apply</button></form></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric href={`/platform/clinics?${qs({})}`} icon={<Building2/>} label="Total tenants" value={all} trend={change(currentClinics, previousClinics)} detail={`${active} active · ${suspended} suspended`}/>{canViewAnalytics && <><Metric href={`/platform/analytics?${qs({})}`} icon={<Users/>} label="New patients" value={currentPatients} trend={change(currentPatients, previousPatients)} detail={`${patients.toLocaleString()} total · ${users} active users`}/><Metric href={`/platform/analytics?${qs({})}`} icon={<CalendarDays/>} label="Appointments" value={currentAppointments} trend={change(currentAppointments, previousAppointments)} detail={`${previousAppointments} in prior period`}/></>}{canViewWhatsApp && <Metric href={`/platform/whatsapp?${qs({})}`} icon={<MessageCircle/>} label="WhatsApp delivery" value={outbound ? `${Math.round((delivered / outbound) * 100)}%` : "—"} trend={0} detail={outbound ? `${delivered} delivered of ${outbound}` : "No outbound messages"}/>}</section>

    <section className="grid gap-4 xl:grid-cols-[.78fr_1.22fr]"><Panel title="Operational health" icon={<HeartPulse className="text-primary"/>}><div className="flex items-center gap-5"><div className="grid size-28 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(var(--primary) ${healthScore}%, var(--muted) 0)` }}><div className="grid size-20 place-items-center rounded-full bg-card"><span className="text-2xl font-bold text-[var(--heading)]">{healthScore}</span></div></div><div className="w-full space-y-2"><Health label="Active tenants" value={`${active}/${all}`}/>{canViewWhatsApp && <><Health label="WhatsApp connected" value={`${connected}/${all}`}/><Health label="Failed jobs" value={failedJobs} danger={failedJobs > 0}/></>}<Health label="Average readiness" value={`${averageReadiness}%`}/></div></div></Panel><Panel title="Tenant activation trend" icon={<Activity className="text-primary"/>}><BarChart points={growth}/><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>{currentClinics} clinics created in period</span><Link href={`/platform/clinics?${qs({})}`} className="font-semibold text-primary">Open tenant directory →</Link></div></Panel></section>

    <section className="grid gap-4 xl:grid-cols-2">{canViewWhatsApp && <Panel title="WhatsApp delivery funnel" icon={<MessageCircle className="text-primary"/>}><Funnel rows={[{ label: "Queued", value: queued }, { label: "Sent", value: sent }, { label: "Delivered", value: delivered }, { label: "Read", value: read }, { label: "Failed", value: messageFailed, danger: true }]} total={Math.max(1, outbound)}/><Link href={`/platform/whatsapp?${qs({})}`} className="mt-4 inline-flex text-xs font-semibold text-primary">Diagnose messaging performance →</Link></Panel>}<Panel title="Readiness risk" icon={<CircleAlert className="text-[var(--warning)]"/>}><div className="grid grid-cols-3 gap-2"><Risk label="Critical" value={severity.critical} tone="danger"/><Risk label="Warning" value={severity.warning} tone="warning"/><Risk label="Watch" value={severity.watch} tone="info"/></div><p className="mt-4 text-xs text-muted-foreground">Severity is based on verified launch-readiness completion: critical below 40%, warning below 80%, and watch below 100%.</p></Panel></section>

    <section className={`grid gap-4 ${canViewLogs ? "xl:grid-cols-[1.12fr_.88fr]" : ""}`}><Panel title="Needs attention" icon={<CircleAlert className="text-[var(--warning)]"/>}>{attention.length ? <div className="space-y-2">{attention.map((clinic) => { const tone = clinic.readiness.percent < 40 ? "danger" : clinic.readiness.percent < 80 ? "warning" : "info"; return <Link key={clinic.id} href={`/platform/clinics/${clinic.id}?range=${range}`} className="block rounded-xl border p-3 hover:bg-muted"><div className="flex items-center justify-between gap-3"><span className="font-semibold">{clinic.brandName || clinic.name}</span><PlatformStatus tone={tone}>{clinic.readiness.percent}% ready</PlatformStatus></div><p className="mt-1 text-xs text-muted-foreground">{clinic.readiness.checks.filter((check) => !check.complete).map((check) => check.label).join(" · ")}</p></Link>; })}</div> : <PlatformState state="success" title="Portfolio ready" description="Every clinic has completed the current readiness checks."/>}</Panel>{canViewLogs && <Panel title="Recent activity" icon={<Activity className="text-primary"/>}><nav className="mb-3 flex flex-wrap gap-1" aria-label="Activity filters">{["all", "security", "tenant", "commercial"].map((filter) => <Link key={filter} href={`?${qs({ activity: filter })}`} className={`rounded-md px-2 py-1 text-xs font-semibold capitalize ${activity === filter ? "bg-primary text-white" : "bg-muted text-muted-foreground"}`}>{filter}</Link>)}</nav>{events.length ? events.map((event) => <div key={event.id} className="border-b py-2.5 first:pt-0 last:border-0"><p className="text-sm font-semibold">{event.action.replaceAll("_", " ")}</p><p className="text-xs text-muted-foreground">{event.clinic.brandName || event.clinic.name} · {event.user?.fullName || "System"} · {event.createdAt.toLocaleDateString("en-IN")}</p></div>) : <PlatformState title="No matching activity" description="Try another activity filter or reporting period."/>}</Panel>}</section>
  </main>;
}

function Metric({ href, icon, label, value, trend, detail }: { href: string; icon: React.ReactNode; label: string; value: number | string; trend: number; detail: string }) { const TrendIcon = trend > 0 ? ArrowUpRight : trend < 0 ? ArrowDownRight : Minus; return <Link href={href} className="rounded-2xl border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><span className="text-primary">{icon}</span><span className={`flex items-center text-xs font-semibold ${trend > 0 ? "text-[var(--success)]" : trend < 0 ? "text-[var(--danger)]" : "text-muted-foreground"}`}><TrendIcon className="size-3.5"/>{Math.abs(trend)}%</span></div><p className="mt-3 text-sm text-muted-foreground">{label}</p><p className="text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></Link>; }
function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <article className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2">{icon}<h2 className="font-bold">{title}</h2></div><div className="mt-4">{children}</div></article>; }
function Health({ label, value, danger = false }: { label: string; value: string | number; danger?: boolean }) { return <div className="flex items-center justify-between border-b py-2 text-sm last:border-0"><span className="text-muted-foreground">{label}</span><b className={danger ? "text-[var(--danger)]" : "text-[var(--heading)]"}>{value}</b></div>; }
function Risk({ label, value, tone }: { label: string; value: number; tone: "danger" | "warning" | "info" }) { return <div className="rounded-xl border bg-muted/30 p-3"><PlatformStatus tone={tone}>{label}</PlatformStatus><p className="mt-2 text-2xl font-bold">{value}</p><span className="text-xs text-muted-foreground">clinic{value === 1 ? "" : "s"}</span></div>; }
function Funnel({ rows, total }: { rows: { label: string; value: number; danger?: boolean }[]; total: number }) { return <div className="space-y-3">{rows.map((row) => <div key={row.label}><div className="mb-1 flex justify-between text-xs"><span className="font-semibold">{row.label}</span><span className={row.danger && row.value ? "font-bold text-[var(--danger)]" : "text-muted-foreground"}>{row.value}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${row.danger ? "bg-[var(--danger)]" : "bg-primary"}`} style={{ width: `${Math.max(row.value ? 3 : 0, Math.min(100, (row.value / total) * 100))}%` }}/></div></div>)}</div>; }
function BarChart({ points }: { points: { label: string; value: number }[] }) { const max = Math.max(1, ...points.map((point) => point.value)); return <div className="flex h-40 items-end gap-2 border-b border-l px-2 pt-3" role="img" aria-label="Tenant activations over the selected period">{points.map((point) => <div key={point.label} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-1"><span className="text-[10px] font-semibold text-muted-foreground">{point.value || ""}</span><div className="w-full max-w-10 rounded-t bg-primary/80" style={{ height: `${Math.max(point.value ? 8 : 2, (point.value / max) * 105)}px` }}/><span className="w-full truncate text-center text-[9px] text-muted-foreground">{point.label}</span></div>)}</div>; }
