"use client";

import { useCallback, useEffect, useState, useTransition } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Search, X } from "lucide-react";

export default function AppointmentFilters() {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const [search, setSearch] = useState(searchParams.get("search") ?? ""); const [isPending, startTransition] = useTransition();
  const update = useCallback((values: Record<string, string>) => { const params = new URLSearchParams(searchParams.toString()); Object.entries(values).forEach(([key, value]) => value ? params.set(key, value) : params.delete(key)); params.delete("page"); startTransition(() => router.replace(`${pathname}?${params.toString()}`, { scroll: false })); }, [pathname, router, searchParams, startTransition]);
  useEffect(() => { const timer = window.setTimeout(() => { if (search !== (searchParams.get("search") ?? "")) update({ search: search.trim() }); }, 350); return () => window.clearTimeout(timer); }, [search, searchParams, update]);
  const hasFilters = Boolean(searchParams.get("search") || searchParams.get("status") || searchParams.get("sort"));
  return <div aria-busy={isPending} className="flex flex-col gap-3 rounded-lg border bg-card p-4 lg:flex-row"><label className="relative flex-1"><span className="sr-only">Search appointments</span><Search className="pointer-events-none absolute left-3 top-3 size-4 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search patient, phone, or treatment…" className="h-10 w-full rounded-md border bg-background pl-9 pr-3 text-sm outline-none ring-offset-background focus:ring-2 focus:ring-ring" /></label><select aria-label="Filter by status" value={searchParams.get("status") ?? ""} onChange={(event) => update({ status: event.target.value })} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">All statuses</option><option>Pending</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option><option>No-show</option></select><select aria-label="Sort appointments" value={searchParams.get("sort") ?? "dateAsc"} onChange={(event) => update({ sort: event.target.value === "dateAsc" ? "" : event.target.value })} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="dateAsc">Soonest first</option><option value="dateDesc">Latest first</option><option value="newest">Recently created</option><option value="oldest">Oldest created</option></select>{hasFilters && <button onClick={() => { setSearch(""); update({ search: "", status: "", sort: "" }); }} className="inline-flex h-10 items-center justify-center gap-2 rounded-md px-3 text-sm font-medium text-muted-foreground hover:bg-muted"><X className="size-4" /> Clear</button>}</div>;
}
