import { Plus } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requirePlatformPermission } from "@/lib/platform";
import { createSupportTicketAction, setSupportTicketStatusAction } from "../actions";

export default async function SupportPage() {
  await requirePlatformPermission("support.manage");
  const [tickets, clinics] = await Promise.all([
    prisma.platformSupportTicket.findMany({ orderBy: [{ status: "asc" }, { updatedAt: "desc" }], take: 100 }),
    prisma.clinic.findMany({ select: { id: true, name: true, brandName: true }, orderBy: { name: "asc" } }),
  ]);
  const open = tickets.filter((ticket) => ticket.status === "OPEN").length;
  const investigating = tickets.filter((ticket) => ticket.status === "INVESTIGATING").length;
  const waiting = tickets.filter((ticket) => ticket.status.includes("WAITING")).length;
  const high = tickets.filter((ticket) => ["HIGH", "CRITICAL"].includes(ticket.priority)).length;
  return <main className="space-y-6 pb-12"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#176b87]">Customers · support</p><h1 className="mt-1 text-3xl font-bold">Support workspace</h1><p className="mt-2 text-sm text-muted-foreground">Platform-only tickets. Do not include patient data, credentials, or sensitive clinical details.</p></div><details className="group relative"><summary className="flex h-10 cursor-pointer list-none items-center gap-2 rounded-xl bg-[#176b87] px-4 text-sm font-bold text-white marker:hidden"><Plus className="size-4"/>Create ticket</summary><section className="absolute right-0 z-20 mt-2 w-[min(34rem,calc(100vw-2rem))] rounded-2xl border bg-white p-5 shadow-xl"><h2 className="font-bold text-[#123b5d]">Open support ticket</h2><form action={createSupportTicketAction} className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">Tenant<select name="clinicId" className="mt-1 block w-full"><option value="">Platform-wide</option>{clinics.map((clinic) => <option key={clinic.id} value={clinic.id}>{clinic.brandName || clinic.name}</option>)}</select></label><label className="text-sm font-semibold">Priority<select name="priority" defaultValue="NORMAL" className="mt-1 block w-full"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></label><label className="text-sm font-semibold md:col-span-2">Subject<input required name="subject" className="mt-1 block w-full"/></label><label className="text-sm font-semibold md:col-span-2">Description<textarea required name="description" className="mt-1 block min-h-28 w-full"/></label><button className="w-fit rounded-xl bg-[#123b5d] px-4 py-2 text-sm font-bold text-white">Create ticket</button></form></section></details></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Open" value={open}/><Kpi label="In progress" value={investigating}/><Kpi label="Waiting" value={waiting}/><Kpi label="High priority" value={high} alert={high > 0}/></section>
    <section className="overflow-hidden rounded-2xl border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-bold">Ticket queue</h2><p className="mt-1 text-xs text-muted-foreground">Newest operational updates appear first within each status.</p></div><span className="text-xs font-semibold text-muted-foreground">{tickets.length} ticket{tickets.length === 1 ? "" : "s"}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr><th className="px-5 py-3">Ticket</th><th className="px-5 py-3">Tenant</th><th className="px-5 py-3">Priority</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Updated</th><th className="px-5 py-3"><span className="sr-only">Update</span></th></tr></thead><tbody>{tickets.map((ticket) => <tr key={ticket.id}><td className="px-5 py-4"><p className="font-semibold">#{ticket.id} · {ticket.subject}</p><p className="mt-1 max-w-md truncate text-xs text-muted-foreground">{ticket.description}</p></td><td className="px-5 py-4 text-xs text-muted-foreground">{ticket.clinicId ? `Clinic #${ticket.clinicId}` : "Platform-wide"}</td><td className="px-5 py-4"><Status value={ticket.priority}/></td><td className="px-5 py-4"><Status value={ticket.status}/></td><td className="px-5 py-4 text-xs text-muted-foreground">{ticket.updatedAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</td><td className="px-5 py-4"><form action={setSupportTicketStatusAction} className="flex items-center gap-2"><input type="hidden" name="ticketId" value={ticket.id}/><select name="status" defaultValue={ticket.status} aria-label={`Status for ticket ${ticket.id}`} className="text-xs"><option>OPEN</option><option>INVESTIGATING</option><option>RESOLVED</option><option>IGNORED</option></select><button className="rounded-lg border px-3 text-xs font-semibold">Save</button></form></td></tr>)}{!tickets.length && <tr><td colSpan={6} className="px-5 py-10 text-center text-sm text-muted-foreground">No support tickets yet. Use Create ticket when a platform issue needs follow-up.</td></tr>}</tbody></table></div></section>
  </main>;
}

function Kpi({ label, value, alert = false }: { label: string; value: number; alert?: boolean }) { return <article className="rounded-xl border bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-1 text-2xl font-bold ${alert ? "text-rose-700" : "text-[#123b5d]"}`}>{value}</p></article>; }
function Status({ value }: { value: string }) { const tone = ["CRITICAL", "HIGH"].includes(value) ? "bg-rose-50 text-rose-700" : ["OPEN", "INVESTIGATING"].includes(value) ? "bg-amber-50 text-amber-800" : ["RESOLVED"].includes(value) ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-700"; return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tone}`}>{value.replaceAll("_", " ")}</span>; }
