export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AlertTriangle, CheckCircle2, Clock3, FileDown, FlaskConical, Image as ImageIcon, MessageSquare, Paperclip, ShieldCheck } from "lucide-react";
import { LabAttachmentUploader } from "@/components/laboratory/LabAttachmentUploader";
import { LabPortalActionForm } from "@/components/laboratory/LabPortalActionForm";
import { signedLabAttachmentPath, signedLabImagingPath } from "@/lib/laboratory-access";
import { allowedLabTransitions, isLabCaseStatus } from "@/lib/laboratory-core";
import { markLabPortalViewed } from "@/lib/laboratory-portal";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = { title: "Secure laboratory case · ConphiDent", robots: { index: false, follow: false, nocache: true } };

function date(value: Date | null | undefined) {
  return value ? value.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not recorded";
}

export default async function LabPortalCasePage({ params }: { params: Promise<{ token: string }> }) {
  const token = (await params).token;
  const viewed = await markLabPortalViewed(token);
  if (!viewed) notFound();
  const access = await prisma.labPortalAccess.findFirst({
    where: { id: viewed.id, tokenHash: viewed.tokenHash, revokedAt: null, expiresAt: { gt: new Date() } },
    include: {
      laboratory: true,
      labCase: {
        include: {
          messages: { orderBy: { createdAt: "asc" }, include: { authorUser: { select: { fullName: true } } } },
          caseAttachments: { orderBy: { createdAt: "desc" } },
          imagingLinks: { include: { imagingStudy: { include: { assets: { where: { role: { in: ["PREVIEW", "THUMBNAIL", "ORIGINAL"] } }, take: 1 } } } } },
          events: { orderBy: { createdAt: "desc" }, take: 50 },
        },
      },
    },
  });
  if (!access) notFound();
  const item = access.labCase;
  const transitions = isLabCaseStatus(item.status) ? allowedLabTransitions(item.status, "LAB") : [];
  const canAccept = transitions.includes("ACCEPTED");
  const canReject = transitions.includes("REJECTED");
  const canClarify = transitions.includes("CLARIFICATION_REQUESTED");
  const productionStates = transitions.filter((state) => ["IN_PRODUCTION", "STAGE_REVIEW", "READY", "DISPATCHED"].includes(state));

  return <main className="min-h-screen bg-muted px-4 py-8 text-heading sm:px-6"><div className="mx-auto max-w-6xl space-y-6">
    <header className="rounded-card bg-heading p-7 text-white shadow-[var(--shadow-overlay)]"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-secondary"><ShieldCheck className="size-4"/>Secure laboratory workspace</p><h1 className="mt-2 text-3xl font-bold">{item.orderNumber || `LAB-${item.id}`}</h1><p className="mt-2 text-sm text-white/75">{access.laboratory.name} · case subject {item.patientSafeIdentifier}</p></div><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-bold">{item.status.replaceAll("_", " ")}</span></div><p className="mt-5 rounded-control bg-white/5 p-3 text-xs text-white/75">This link is unique, revocable, and expires {date(access.expiresAt)}. Do not forward it. Patient name, phone, date of birth, address, and billing data are intentionally excluded.</p></header>

    <section className="space-y-5"><article className="rounded-card border bg-white p-6 shadow-[var(--shadow)]"><h2 className="flex items-center gap-2 text-xl font-bold"><FlaskConical className="size-5 text-primary"/>Approved work authorization</h2><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2 xl:grid-cols-3">{[["Procedure", item.restorationType || item.caseType], ["Teeth / scope", item.teeth ? `FDI ${item.teeth}` : item.anatomicalScope], ["Material", item.material], ["Shade", [item.shade, item.shadeSystem].filter(Boolean).join(" · ")], ["Required in clinic", date(item.dueDate)], ["Priority", item.priority], ["Margin", item.marginDesign || item.marginType], ["Pontic", item.ponticDesign], ["Implant system", item.implantSystem], ["Implant components", item.implantComponents], ["Checkpoints", item.requestedStages.join(", ")], ["Pickup", item.pickupRequired ? item.pickupInstructions || "Required" : "Not requested"]].map(([label, value]) => <div key={String(label)}><dt className="text-xs font-bold uppercase tracking-wide text-text-muted">{label}</dt><dd className="mt-1 font-semibold">{value || "—"}</dd></div>)}</dl>{item.notes || item.occlusionNotes || item.biteNotes ? <div className="mt-5 space-y-3">{[["Instructions", item.notes], ["Occlusion", item.occlusionNotes], ["Bite / design", item.biteNotes]].filter(([, value]) => value).map(([label, value]) => <div key={String(label)} className="rounded-control bg-muted p-3 text-sm"><b>{label}</b><p className="mt-1 whitespace-pre-wrap">{value}</p></div>)}</div> : null}</article>
      <aside className="space-y-4">{canAccept ? <LabPortalActionForm token={token} actionType="ACCEPT" label="Accept order"><label className="text-sm font-semibold">Expected completion date<input required name="expectedCompletionAt" type="date" className="mt-1 h-11 w-full rounded-control border px-3"/></label><label className="text-sm font-semibold">Acceptance note<textarea name="body" maxLength={4000} className="mt-1 min-h-20 w-full rounded-control border p-3"/></label></LabPortalActionForm> : null}{canClarify ? <LabPortalActionForm token={token} actionType="CLARIFY" label="Request clarification"><label className="text-sm font-semibold">Clarification needed<textarea required minLength={8} maxLength={4000} name="body" className="mt-1 min-h-24 w-full rounded-control border p-3"/></label></LabPortalActionForm> : null}{canReject ? <LabPortalActionForm token={token} actionType="REJECT" label="Reject order" destructive><label className="text-sm font-semibold">Reason<textarea required minLength={8} maxLength={4000} name="body" className="mt-1 min-h-24 w-full rounded-control border p-3"/></label></LabPortalActionForm> : null}{productionStates.length ? <LabPortalActionForm token={token} actionType="STATUS" label="Commit production status"><label className="text-sm font-semibold">Next status<select required name="status" className="mt-1 h-11 w-full rounded-control border px-3"><option value="">Choose status</option>{productionStates.map((state) => <option key={state} value={state}>{state.replaceAll("_", " ")}</option>)}</select></label><label className="text-sm font-semibold">Material and batch details<textarea name="materialBatchDetails" maxLength={1000} className="mt-1 min-h-20 w-full rounded-control border p-3" placeholder="Material lot/batch, manufacturer, component references"/></label><div className="grid gap-2 sm:grid-cols-2"><label className="text-sm font-semibold">Dispatch carrier<input name="dispatchCarrier" maxLength={160} className="mt-1 h-11 w-full rounded-control border px-3"/></label><label className="text-sm font-semibold">Tracking reference<input name="dispatchTrackingNumber" maxLength={160} className="mt-1 h-11 w-full rounded-control border px-3"/></label></div><label className="text-sm font-semibold">Dispatch / production note<textarea name="dispatchNotes" maxLength={1000} className="mt-1 min-h-20 w-full rounded-control border p-3"/></label><label className="text-sm font-semibold">Update for clinic thread<textarea name="body" maxLength={4000} className="mt-1 min-h-20 w-full rounded-control border p-3"/></label></LabPortalActionForm> : null}{!canAccept && !canReject && !canClarify && !productionStates.length ? <div className="rounded-card border bg-white p-5"><CheckCircle2 className="size-5 text-success"/><p className="mt-2 font-bold">No laboratory status action is currently due.</p><p className="mt-1 text-sm text-text-muted">Messages and permitted file uploads remain available.</p></div> : null}</aside></section>

    <section className="space-y-5"><article className="rounded-card border bg-white p-5 shadow-[var(--shadow)]"><h2 className="flex items-center gap-2 text-lg font-bold"><MessageSquare className="size-5 text-primary"/>Case thread</h2><div className="mt-4 max-h-96 space-y-3 overflow-y-auto">{item.messages.map((message) => <div key={message.id} className={`rounded-control p-3 text-sm ${message.authorType === "LAB" ? "bg-secondary" : "bg-muted"}`}><p className="text-xs font-bold uppercase text-text-muted">{message.authorType === "LAB" ? access.laboratory.name : "Clinic team"} · {date(message.createdAt)}</p><p className="mt-1 whitespace-pre-wrap">{message.body}</p></div>)}{!item.messages.length ? <p className="text-sm text-text-muted">No messages yet.</p> : null}</div><LabPortalActionForm token={token} actionType="MESSAGE" label="Post message"><label className="text-sm font-semibold">Message<textarea required minLength={2} maxLength={4000} name="body" className="mt-1 min-h-24 w-full rounded-control border p-3"/></label></LabPortalActionForm></article>
      <article className="rounded-card border bg-white p-5 shadow-[var(--shadow)]"><h2 className="flex items-center gap-2 text-lg font-bold"><Paperclip className="size-5 text-primary"/>Case files</h2><p className="mt-1 text-sm text-text-muted">Upload only case-specific production files. Files are private, signature-checked, and attached permanently to this case.</p><div className="mt-4"><LabAttachmentUploader caseId={item.id} portalToken={token}/></div><div className="mt-4 divide-y">{item.caseAttachments.map((attachment) => <a key={attachment.id} href={signedLabAttachmentPath(attachment.id, `portal:${access.id}`)} className="flex items-center justify-between gap-3 py-3 text-sm text-primary"><span className="min-w-0"><b className="block truncate">{attachment.originalName}</b><span className="text-xs text-text-muted">{attachment.category.replaceAll("_", " ")} · {(attachment.sizeBytes / 1024 / 1024).toFixed(1)} MB</span></span><FileDown className="size-4 shrink-0"/></a>)}{!item.caseAttachments.length ? <p className="py-4 text-sm text-text-muted">No case files.</p> : null}</div></article></section>

    {item.imagingLinks.length ? <section className="rounded-card border bg-white p-5 shadow-[var(--shadow)]"><h2 className="flex items-center gap-2 text-lg font-bold"><ImageIcon className="size-5 text-primary"/>Approved imaging references</h2><p className="mt-1 text-sm text-text-muted">Each link is short-lived and valid only inside this case access grant.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{item.imagingLinks.map((link) => { const asset = link.imagingStudy.assets[0]; return <article key={link.id} className="rounded-control border p-4"><p className="font-bold">{link.imagingStudy.modality.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-text-muted">{link.purpose.replaceAll("_", " ")} · {date(link.imagingStudy.acquisitionDate)}</p>{asset ? <a href={signedLabImagingPath(asset.id, access.id)} className="mt-3 inline-flex rounded-control bg-heading px-3 py-2 text-xs font-semibold text-white">Open reference</a> : <p className="mt-3 text-xs text-warning">No viewable asset is attached.</p>}</article>})}</div></section> : null}

    <section className="rounded-card border bg-white p-5 shadow-[var(--shadow)]"><h2 className="flex items-center gap-2 text-lg font-bold"><Clock3 className="size-5 text-primary"/>Case activity</h2><div className="mt-4 grid gap-3 lg:grid-cols-2">{item.events.map((event) => <div key={event.id} className="rounded-control bg-muted p-3 text-sm"><div className="flex justify-between gap-3"><b>{event.type.replaceAll("_", " ")}</b><time className="text-xs text-text-muted">{date(event.createdAt)}</time></div><p className="mt-1 text-xs text-text-muted">{event.actorType} · {event.actorName || "system"}</p>{event.notes ? <p className="mt-2">{event.notes}</p> : null}</div>)}</div></section>
    <p className="flex items-center gap-2 rounded-control bg-warning-bg p-4 text-xs text-warning"><AlertTriangle className="size-4"/>For urgent clinical clarification, use this case thread so the clinic receives a permanent, attributable notification. Do not identify the patient in external messages.</p>
  </div></main>;
}
