"use client";

import { useState } from "react";

const steps = ["Organization", "Branding", "Location", "Doctors & staff", "Hours", "Services", "WhatsApp", "Features", "Subscription", "Domain", "Review & activate"];
const services = ["Dentures", "Implants", "Root Canals", "Braces", "Aesthetic Dentistry", "Kids Dentistry", "Gum Treatment", "Extractions", "Surgeries", "X-Ray"];
const features = ["patients", "appointments", "clinical", "billing", "crm", "follow_ups", "whatsapp", "laboratory", "inventory", "reports", "analytics", "ai_coach"];

export function ClinicOnboardingWizard({ action, plans }: { action: (formData: FormData) => void | Promise<void>; plans: { id: number; name: string }[] }) {
  const [step, setStep] = useState(0); const next = () => setStep((value) => Math.min(value + 1, steps.length - 1)); const previous = () => setStep((value) => Math.max(value - 1, 0));
  return <section className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Add clinic</h2><p className="mt-1 text-sm text-muted-foreground">A structured, database-backed tenant provisioning flow.</p></div><span className="rounded-full bg-sky-50 px-3 py-1 text-sm font-bold text-sky-700">{step + 1} / {steps.length}</span></div><ol className="mt-5 flex gap-2 overflow-x-auto pb-1">{steps.map((name, index) => <li key={name} className={`shrink-0 rounded-full px-3 py-1 text-xs font-semibold ${index === step ? "bg-sky-700 text-white" : index < step ? "bg-emerald-50 text-emerald-700" : "bg-muted text-muted-foreground"}`}>{name}</li>)}</ol><form action={action} className="mt-6">
    <div hidden={step !== 0} className="grid gap-4 md:grid-cols-2"><Field label="Legal clinic name" name="name"/><Field label="First owner name" name="ownerName"/><Field label="Owner email" name="ownerEmail" type="email"/><Field label="Temporary owner password" name="password" type="password" minLength={12}/></div>
    <div hidden={step !== 1} className="grid gap-4 md:grid-cols-2"><Field label="Display brand name" name="brandName"/><p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground md:col-span-2">Logo upload becomes available immediately after activation in the clinic control workspace. It requires configured Blob storage and is not simulated here.</p></div>
    <div hidden={step !== 2} className="grid gap-4 md:grid-cols-2"><Field label="Primary branch name" name="locationName"/><Field label="Branch phone" name="locationPhone" required={false}/><Field label="Branch address" name="locationAddress" className="md:col-span-2" required={false}/><Field label="Timezone" name="timezone" defaultValue="Asia/Kolkata"/></div>
    <div hidden={step !== 3} className="grid gap-4"><Field label="Primary doctor/provider" name="providerName" required={false}/><p className="text-sm text-muted-foreground">Additional staff accounts are created after activation from the clinic’s access controls, so each receives proper credentials.</p></div>
    <div hidden={step !== 4}><p className="rounded-xl border p-4 text-sm text-muted-foreground">The initial branch receives the validated standard schedule (09:00–18:00, 30-minute slots). Adjust every branch schedule in the control workspace after activation.</p></div>
    <fieldset hidden={step !== 5}><legend className="font-semibold">Initial services</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{services.map((name) => <label key={name} className="rounded-lg border p-3 text-sm"><input name="serviceName" type="checkbox" value={name} defaultChecked className="mr-2"/>{name}</label>)}</div></fieldset>
    <div hidden={step !== 6} className="grid gap-4"><Field label="English welcome message" name="welcomeEnglish" required={false}/><Field label="Hindi welcome message" name="welcomeHindi" required={false}/><p className="text-sm text-muted-foreground">Meta phone/WABA connection is intentionally completed later from the tenant WhatsApp settings; no shared fallback is created.</p></div>
    <fieldset hidden={step !== 7}><legend className="font-semibold">Enable tenant features</legend><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{features.map((key) => <label key={key} className="rounded-lg border p-3 text-sm"><input name="featureKey" type="checkbox" value={key} defaultChecked className="mr-2"/>{key.replace("_", " ")}</label>)}</div></fieldset>
    <div hidden={step !== 8} className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Subscription plan<select name="planId" className="mt-1.5 h-11 w-full rounded-xl border bg-background px-3"><option value="">No plan / configure later</option>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><label className="text-sm font-semibold">Initial status<select name="subscriptionStatus" className="mt-1.5 h-11 w-full rounded-xl border bg-background px-3"><option value="TRIAL">Trial</option><option value="ACTIVE">Active</option></select></label></div>
    <div hidden={step !== 9}><Field label="Workspace URL key" name="slug" pattern="[a-zA-Z0-9 -]+" placeholder="smile-dental-pune"/><p className="mt-3 text-sm text-muted-foreground">The workspace key is normalized and checked for uniqueness before activation.</p></div>
    <div hidden={step !== 10} className="rounded-xl border bg-muted/30 p-5 text-sm"><p className="font-bold">Ready to activate</p><p className="mt-2 text-muted-foreground">This provisions the tenant, primary location, location hours, selected services, provider, WhatsApp configuration shell, feature entitlements, subscription, owner account, checklist, and audit record in one database operation.</p></div>
    <div className="mt-6 flex justify-between gap-3">{step > 0 ? <button type="button" onClick={previous} className="h-11 rounded-xl border px-5 font-semibold">Back</button> : <span/>}{step < steps.length - 1 ? <button type="button" onClick={next} className="h-11 rounded-xl bg-sky-700 px-5 font-semibold text-white">Continue</button> : <button className="h-11 rounded-xl bg-emerald-600 px-5 font-semibold text-white">Activate clinic</button>}</div>
  </form></section>;
}
function Field({ label, className = "", required = true, ...props }: { label: string; className?: string; required?: boolean } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className={`text-sm font-semibold ${className}`}>{label}<input required={required} {...props} className="mt-1.5 h-11 w-full rounded-xl border bg-background px-3 font-normal"/></label>; }
