import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requirePlatformPermission } from "@/lib/platform";
import { savePlatformOnboardingAction } from "../actions";

const stages = ["LEAD", "QUALIFIED", "DEMO", "AGREEMENT", "TENANT_CREATED", "BUSINESS_DETAILS", "BRANDING", "DOCTORS", "SERVICES", "WHATSAPP_SETUP", "VERIFICATION", "TESTING", "TRAINING", "READY", "LIVE"];

export default async function OnboardingPage() {
  await requirePlatformPermission("onboarding.manage");
  const [clinics, records] = await Promise.all([prisma.clinic.findMany({ orderBy: { createdAt: "desc" } }), prisma.platformOnboarding.findMany()]);
  const byClinic = new Map(records.map((record) => [record.clinicId, record]));
  return <main className="mx-auto max-w-6xl space-y-6 pb-12"><header><Link href="/setup" className="text-sm font-semibold text-[var(--gold)]">← Control centre</Link><p className="platform-eyebrow mt-4">Sales & onboarding</p><h1 className="mt-1 text-3xl font-bold">Onboarding pipeline</h1><p className="mt-2 text-muted-foreground">Persisted operational stages, go-live targets, blockers, and notes for every provisioned tenant.</p></header><section className="space-y-4">{clinics.map((clinic) => { const record = byClinic.get(clinic.id); return <details key={clinic.id} className="rounded-2xl border bg-card p-5 shadow-sm"><summary className="cursor-pointer font-bold">{clinic.brandName || clinic.name} <span className="ml-2 text-sm font-normal text-muted-foreground">{record?.stage || "TENANT_CREATED"} · {record?.targetGoLiveAt ? `Target ${record.targetGoLiveAt.toLocaleDateString("en-IN")}` : "No target date"}</span></summary><form action={savePlatformOnboardingAction} className="mt-5 grid gap-3 md:grid-cols-2"><input type="hidden" name="clinicId" value={clinic.id}/><label className="text-sm font-semibold">Stage<select name="stage" defaultValue={record?.stage || "TENANT_CREATED"} className="mt-1 block h-10 w-full rounded-lg border bg-background px-3">{stages.map((stage) => <option key={stage}>{stage}</option>)}</select></label><label className="text-sm font-semibold">Target go-live<input name="targetGoLiveAt" type="date" defaultValue={record?.targetGoLiveAt?.toISOString().slice(0, 10) || ""} className="mt-1 block h-10 w-full rounded-lg border bg-background px-3"/></label><label className="text-sm font-semibold md:col-span-2">Blockers<textarea name="blockers" defaultValue={record?.blockers || ""} className="mt-1 block min-h-20 w-full rounded-lg border bg-background p-3"/></label><label className="text-sm font-semibold md:col-span-2">Internal notes<textarea name="notes" defaultValue={record?.notes || ""} className="mt-1 block min-h-20 w-full rounded-lg border bg-background p-3"/></label><button className="w-fit platform-button platform-button--primary">Save onboarding record</button></form></details>; })}{!clinics.length && <p className="text-sm text-muted-foreground">No clinics are provisioned yet.</p>}</section></main>;
}
