export const dynamic = "force-dynamic";

import { redirect } from "next/navigation";
import { BotMessageSquare, ShieldCheck, Sparkles } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth";
import { requireFeature } from "@/lib/features";
import { addFaqAction, toggleFaqAction } from "./actions";

export default async function AICoachPage() {
  await requireFeature("ai_coach");
  const user = await requireUser();
  if (user.role !== "OWNER") redirect("/dashboard");
  const faqs = await prisma.clinicFAQ.findMany({ where: { clinicId: user.clinicId }, orderBy: [{ active: "desc" }, { createdAt: "desc" }] });
  return <div className="dashboard-list-page mx-auto max-w-6xl space-y-6">
    <header><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Premium AI</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">AI Conversion Coach</h1><p className="mt-2 text-muted-foreground">Control the clinic-approved answers that help patients move from enquiry to appointment.</p></header>
    <section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-border bg-card p-5 shadow-sm"><BotMessageSquare className="size-6 text-primary" /><h2 className="mt-4 font-bold">Approved answers only</h2><p className="mt-2 text-sm text-muted-foreground">Prices, EMI, treatment questions and offers should be saved here before the AI uses them.</p></article><article className="rounded-2xl border border-border bg-card p-5 shadow-sm"><Sparkles className="size-6 text-violet-600" /><h2 className="mt-4 font-bold">Booking focused</h2><p className="mt-2 text-sm text-muted-foreground">The coach keeps answers concise and directs suitable enquiries toward booking.</p></article><article className="rounded-2xl border border-border bg-card p-5 shadow-sm"><ShieldCheck className="size-6 text-emerald-600" /><h2 className="mt-4 font-bold">Clinical safety</h2><p className="mt-2 text-sm text-muted-foreground">It does not diagnose, prescribe or make unapproved claims.</p></article></section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h2 className="text-lg font-bold">Add an approved answer</h2><p className="mt-1 text-sm text-muted-foreground">Examples: “Does cleaning hurt?”, “Do you offer EMI?”, or “What is the consultation fee?”</p><form action={addFaqAction} className="mt-5 grid gap-3"><input name="question" required placeholder="Patient question" className="h-11 rounded-xl border px-3" /><textarea name="answer" required placeholder="Approved clinic answer. Be clear, friendly and accurate." className="min-h-28 rounded-xl border p-3" /><select name="category" className="h-11 w-full max-w-xs rounded-xl border bg-card px-3"><option value="GENERAL">General</option><option value="PRICING">Pricing</option><option value="EMI">EMI / payment</option><option value="TREATMENT">Treatment</option><option value="OBJECTION">Objection handling</option></select><button className="h-11 w-fit rounded-xl bg-primary px-5 font-semibold text-primary-foreground hover:opacity-90">Save approved answer</button></form></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5"><h2 className="text-lg font-bold">Approved answer library</h2><p className="mt-1 text-sm text-muted-foreground">Only active entries can be used by the WhatsApp AI Coach.</p></div>{faqs.length === 0 ? <p className="px-6 py-12 text-center text-sm text-muted-foreground">No approved answers yet. Add your first clinic FAQ above.</p> : <div className="divide-y divide-border">{faqs.map((faq) => <article key={faq.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{faq.question}</p><span className="rounded-full bg-muted px-2 py-1 text-xs font-semibold text-muted-foreground">{faq.category}</span>{!faq.active && <span className="rounded-full bg-rose-50 px-2 py-1 text-xs font-semibold text-rose-700">Inactive</span>}</div><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{faq.answer}</p></div><form action={toggleFaqAction}><input type="hidden" name="id" value={faq.id} /><input type="hidden" name="active" value={String(!faq.active)} /><button className="shrink-0 rounded-xl border px-4 py-2 text-sm font-semibold hover:bg-muted">{faq.active ? "Disable" : "Enable"}</button></form></article>)}</div>}</section>
  </div>;
}
