import { prisma } from "@/lib/prisma";
import { requirePlatformPermission } from "@/lib/platform";

const periodStart = (range: string, offset = 0) => { const days = range === "7d" ? 7 : range === "90d" ? 90 : 30; const end = new Date(); end.setHours(0, 0, 0, 0); end.setDate(end.getDate() - offset * days); const start = new Date(end); start.setDate(start.getDate() - days); return { start, end }; };

export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ range?: string }> }) {
  await requirePlatformPermission("analytics.read"); const range = ["7d", "30d", "90d"].includes((await searchParams).range || "") ? (await searchParams).range! : "30d"; const current = periodStart(range); const previous = periodStart(range, 1);
  const [clinics, users, patients, appointments, leads, messages, conversations, createdClinics, priorClinics, activeSubscriptions, featureRows] = await Promise.all([
    prisma.clinic.findMany({ select: { id: true, name: true, brandName: true, status: true, _count: { select: { users: true, patients: true, appointments: true, conversations: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.user.count({ where: { active: true } }), prisma.patient.count(), prisma.appointment.count({ where: { createdAt: { gte: current.start, lt: current.end } } }), prisma.lead.count({ where: { createdAt: { gte: current.start, lt: current.end } } }),
    prisma.whatsAppMessage.groupBy({ by: ["direction", "deliveryStatus"], where: { createdAt: { gte: current.start, lt: current.end } }, _count: { _all: true } }), prisma.whatsAppConversation.count({ where: { lastMessageAt: { gte: current.start, lt: current.end } } }),
    prisma.clinic.count({ where: { createdAt: { gte: current.start, lt: current.end } } }), prisma.clinic.count({ where: { createdAt: { gte: previous.start, lt: previous.end } } }), prisma.tenantSubscription.count({ where: { status: "ACTIVE" } }),
    prisma.tenantFeatureEntitlement.groupBy({ by: ["featureKey"], where: { enabled: true }, _count: { clinicId: true } }),
  ]);
  const count = (direction: string, status?: string) => messages.filter((item) => item.direction === direction && (!status || item.deliveryStatus === status)).reduce((sum, item) => sum + item._count._all, 0);
  const outbound = count("OUTBOUND"); const delivered = count("OUTBOUND", "DELIVERED") + count("OUTBOUND", "READ"); const read = count("OUTBOUND", "READ"); const inbound = count("INBOUND"); const change = createdClinics - priorClinics;
  return <main className="space-y-6 pb-12"><header><p className="platform-eyebrow">Analytics</p><h1 className="mt-1 text-3xl font-bold">Platform intelligence</h1><p className="mt-2 text-sm text-text-muted">Aggregated operational data only. No patient names, contact details, clinical notes, or message bodies are shown.</p></header>
    <form className="flex gap-2"><select name="range" defaultValue={range} className="h-10 rounded border px-3"><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select><button className="rounded bg-primary px-4 text-sm font-semibold text-white">Apply</button></form>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active subscriptions" value={activeSubscriptions}/><Metric label="New clinics" value={createdClinics} note={`${change >= 0 ? "+" : ""}${change} vs previous period`}/><Metric label="Active users" value={users}/><Metric label="Patients / appointments" value={`${patients.toLocaleString()} / ${appointments.toLocaleString()}`} note={`Appointments in ${range}`}/></section>
    <section className="space-y-6"><Panel title="WhatsApp performance"><div className="grid grid-cols-2 gap-3 text-sm"><Value label="Inbound" value={inbound}/><Value label="Outbound" value={outbound}/><Value label="Delivered" value={delivered}/><Value label="Read" value={read}/><Value label="Delivery rate" value={outbound ? `${Math.round(delivered / outbound * 100)}%` : "—"}/><Value label="Read rate" value={outbound ? `${Math.round(read / outbound * 100)}%` : "—"}/><Value label="Active conversations" value={conversations}/><Value label="New leads" value={leads}/></div></Panel><Panel title="Feature availability"><p className="text-sm text-text-muted">This is enabled-entitlement coverage, not product-usage telemetry. The application does not yet record module-view or module-action events.</p><div className="mt-4 grid grid-cols-2 gap-2">{featureRows.map((row) => <Value key={row.featureKey} label={row.featureKey.replaceAll("_", " ")} value={`${row._count.clinicId} enabled`}/>)}</div></Panel></section>
    <Panel title="Clinic engagement (observable signals)"><p className="mb-3 text-sm text-text-muted">Classification is transparent: active means at least one stored appointment, conversation, or patient; low activity means users exist but none of those records are present; inactive has no observed users or operations.</p><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr><th>Clinic</th><th>Status</th><th>Users</th><th>Patients</th><th>Appointments</th><th>Conversations</th><th>Observed activity</th></tr></thead><tbody>{clinics.map((clinic) => { const operations = clinic._count.patients + clinic._count.appointments + clinic._count.conversations; const label = operations ? "Active" : clinic._count.users ? "Low activity" : "Inactive"; return <tr key={clinic.id} className="border-t"><td className="py-3 font-semibold">{clinic.brandName || clinic.name}</td><td>{clinic.status}</td><td>{clinic._count.users}</td><td>{clinic._count.patients}</td><td>{clinic._count.appointments}</td><td>{clinic._count.conversations}</td><td>{label}</td></tr>; })}</tbody></table></div></Panel>
  </main>;
}
function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) { return <article className="rounded-xl border bg-white p-4"><p className="text-sm text-text-muted">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p>{note && <p className="mt-1 text-xs text-text-muted">{note}</p>}</article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">{title}</h2><div className="mt-3">{children}</div></section>; }
function Value({ label, value }: { label: string; value: string | number }) { return <div className="rounded border p-3"><p className="text-xs capitalize text-text-muted">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
