import type { Metadata } from "next";
import Link from "next/link";
import PublicShell from "@/components/marketing/PublicShell";

export const metadata: Metadata = { title: "Privacy policy", description: "ConphiDent privacy information.", alternates: { canonical: "/privacy" } };

export default function Privacy() {
  return <PublicShell><section className="mk-page-hero mk-legal-hero"><div className="cf-wrap"><p className="mk-kicker">Privacy</p><h1>Privacy information</h1><p>How ConphiDent handles public enquiries and clinic workspace information.</p></div></section><section className="mk-legal"><div className="cf-wrap"><h2>Public website information</h2><p>When you request a demonstration, ConphiDent stores the contact and clinic information you provide so the team can respond to your enquiry. Do not submit patient health information through the demo form.</p><h2>Clinic application data</h2><p>Each clinic workspace is account-controlled and access is limited by staff role. Clinics remain responsible for entering accurate data, obtaining required patient permissions, and using the platform in accordance with applicable law and their agreement with ConphiDent.</p><h2>WhatsApp communications</h2><p>Clinic staff must send WhatsApp messages only to confirmed numbers and with appropriate consent. A recipient may reply STOP, UNSUBSCRIBE, or an equivalent request to stop non-essential WhatsApp communications; they can reply START to opt in again.</p><h2>Retention and deletion requests</h2><p>We retain information only for as long as needed to operate the service, meet legal obligations, resolve disputes, and enforce agreements. A clinic or individual may request access, correction, or deletion by following our <Link href="/data-deletion">data deletion process</Link>. Requests are reviewed after identity and authority are verified.</p><h2>Product previews</h2><p>Public product screenshots use sanitized, fictional demonstration data and are not real patient records.</p><h2>Contact</h2><p>For privacy questions, email <a href="mailto:contact@conphident.live">contact@conphident.live</a> with the subject “Privacy request”.</p><p className="mk-legal-note">Last updated: 8 August 2026.</p></div></section></PublicShell>;
}
