import Link from "next/link";
import { ArrowRight, BarChart3, Bot, CalendarDays, Check, ChevronDown, CircleDollarSign, ClipboardList, Crown, FlaskConical, HeartPulse, MapPin, MessageCircle, Package, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import DemoForm from "@/components/marketing/DemoForm";
import DashboardShowcase from "@/components/marketing/DashboardShowcase";

const whatsappHref = process.env.NEXT_PUBLIC_WHATSAPP_URL || "#demo";
const features = [
  [Bot, "AI Receptionist", "Responds instantly, qualifies intent and moves patients toward the right next step."],
  [MessageCircle, "WhatsApp automation", "Turn your busiest channel into an organised, conversion-ready patient journey."],
  [UsersRound, "Patient CRM", "Every conversation, treatment context and relationship in one patient record."],
  [CalendarDays, "Smart scheduling", "Coordinate doctors, chairs and patients without the front-desk friction."],
  [CircleDollarSign, "Billing & invoicing", "Create invoices, track collections and see financial health in real time."],
  [ClipboardList, "Clinical workspace", "Plans, records, prescriptions and odontograms designed for daily care."],
  [Package, "Inventory control", "See what is running low before a treatment day is affected."],
  [FlaskConical, "Lab management", "Track cases, due dates, revisions and payments with complete confidence."],
  [BarChart3, "Reports & analytics", "Turn live operational signals into better decisions, faster."],
  [ShieldCheck, "Role-aware access", "Give every team member precisely the access they need—nothing more."],
  [MapPin, "Multi-location ready", "Operate one clinic or a growing group from a platform built to scale."],
  [HeartPulse, "Built for care", "A calm, connected operating layer that helps teams spend more time with patients."],
] as const;
const steps = ["Lead", "Patient", "Appointment", "Treatment", "Invoice", "Follow-up", "Review"];

function Mark() { return <span aria-hidden className="grid size-8 place-items-center rounded-[11px] bg-gradient-to-br from-cyan-300 via-blue-500 to-violet-600 shadow-lg shadow-blue-500/20"><span className="size-3.5 rounded-[45%] border-[3px] border-white" /></span>; }

export default function Home() {
  return <main className="conphident-marketing min-h-screen overflow-hidden bg-[#07131a] text-slate-100 selection:bg-cyan-300 selection:text-slate-950">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@graph": [{ "@type": "Organization", name: "ConphiDent", url: "https://www.conphident.live", description: "The operating system for modern dental clinics." }, { "@type": "SoftwareApplication", name: "ConphiDent", applicationCategory: "BusinessApplication", operatingSystem: "Web", url: "https://www.conphident.live" }] }) }} />
    <div className="pointer-events-none absolute inset-x-0 top-0 h-[780px] bg-[radial-gradient(ellipse_at_50%_-10%,rgba(32,170,190,.28),transparent_54%),radial-gradient(ellipse_at_88%_22%,rgba(112,77,255,.16),transparent_32%)]" />
    <nav className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8" aria-label="Main navigation">
      <Link href="/" className="flex items-center gap-2.5 text-lg font-bold tracking-[-.06em]"><Mark /> Conphi<span className="text-cyan-300">Dent</span></Link>
      <div className="hidden items-center gap-7 text-sm text-slate-300 md:flex"><a href="#platform" className="hover:text-white">Platform</a><a href="#workflow" className="hover:text-white">Workflow</a><a href="#pricing" className="hover:text-white">Pricing</a><a href="#demo" className="hover:text-white">Contact</a></div>
      <div className="flex items-center gap-3"><Link href="/login" className="hidden text-sm font-medium text-slate-300 hover:text-white sm:block">Sign in</Link><a href="#demo" className="rounded-full bg-white px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-cyan-200">Book demo</a></div>
    </nav>

    <section className="relative mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-16 lg:grid-cols-[.95fr_1.05fr] lg:px-8 lg:pb-32 lg:pt-24">
      <div className="self-center"><p className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-200/15 bg-white/5 px-3 py-1.5 text-xs font-semibold text-cyan-100"><Sparkles className="size-3.5 text-cyan-300" /> THE OPERATING SYSTEM FOR MODERN DENTAL CLINICS</p><h1 className="max-w-xl text-5xl font-semibold tracking-[-.075em] text-white sm:text-6xl lg:text-7xl">A better clinic day, <span className="bg-gradient-to-r from-cyan-200 to-violet-300 bg-clip-text text-transparent">by design.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-300 sm:text-lg">ConphiDent connects your front desk, WhatsApp, clinical work, billing and operations in one calm, intelligent workspace.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#demo" className="inline-flex items-center gap-2 rounded-full bg-cyan-300 px-5 py-3.5 text-sm font-bold text-slate-950 shadow-xl shadow-cyan-400/15 transition hover:-translate-y-0.5 hover:bg-cyan-200">Book a demo <ArrowRight className="size-4" /></a><a href="#pricing" className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-5 py-3.5 text-sm font-bold text-white transition hover:bg-white/10">Start free trial</a><a href={whatsappHref} className="inline-flex items-center gap-2 px-3 py-3 text-sm font-semibold text-emerald-300 hover:text-emerald-200"><MessageCircle className="size-4" /> Chat on WhatsApp</a></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs font-medium text-slate-400"><span className="inline-flex items-center gap-2"><Check className="size-4 text-cyan-300" /> Built for dental teams</span><span className="inline-flex items-center gap-2"><Check className="size-4 text-cyan-300" /> Multi-tenant by design</span><span className="inline-flex items-center gap-2"><Check className="size-4 text-cyan-300" /> India-ready workflows</span></div></div>
      <div className="relative"><div className="absolute -inset-10 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative overflow-hidden rounded-[28px] border border-white/15 bg-slate-950/55 p-2 shadow-2xl shadow-black/50 backdrop-blur-xl"><div className="rounded-[22px] border border-white/10 bg-[#0c1c25] p-4 sm:p-6"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-2"><Mark /><span className="text-sm font-bold">ConphiDent</span></div><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-[10px] font-bold text-emerald-300">ALL SYSTEMS LIVE</span></div><div className="grid gap-3 sm:grid-cols-3">{[["Appointments", "24", "+12%"],["Collections", "₹1.48L", "+18%"],["Follow-ups", "16", "Today"]].map(([label,value,delta])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-3"><p className="text-[10px] text-slate-400">{label}</p><b className="mt-1 block text-xl tracking-tight text-white">{value}</b><span className="text-[10px] font-bold text-emerald-300">{delta}</span></div>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-[1.35fr_.9fr]"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="flex justify-between text-xs"><b>Revenue overview</b><span className="text-slate-400">Last 7 days</span></div><div className="mt-8 flex h-20 items-end gap-2">{[33,48,39,64,51,72,88].map((h,i)=><i key={i} style={{height:`${h}%`}} className="block flex-1 rounded-t-md bg-gradient-to-t from-cyan-500 to-blue-300" />)}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><b className="text-xs">Next patients</b>{["Ananya Shah","Rahul Verma","Zoya Khan"].map((name,i)=><div className="mt-3 flex items-center gap-2" key={name}><span className="size-6 rounded-full bg-gradient-to-br from-violet-300 to-cyan-300" /><div><b className="block text-[10px]">{name}</b><small className="text-[9px] text-slate-400">{9+i}:30 AM · Confirmed</small></div></div>)}</div></div></div></div></div>
    </section>

    <section className="border-y border-white/8 bg-white/[.025] py-8"><div className="mx-auto max-w-7xl px-5 text-center lg:px-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Designed for clinics that choose clarity over chaos</p><div className="mt-6 grid grid-cols-2 gap-4 text-sm font-semibold text-slate-400 sm:grid-cols-4"><span>Patient-first</span><span>Secure by design</span><span>One team, one view</span><span>Built to scale</span></div></div></section>

    <section id="platform" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><p className="text-xs font-bold tracking-[.18em] text-cyan-300">ONE PLATFORM, FULL CLINIC CLARITY</p><div className="mt-4 flex flex-wrap justify-between gap-6"><h2 className="max-w-2xl text-4xl font-semibold tracking-[-.06em] text-white sm:text-5xl">Everything your clinic needs to move with confidence.</h2><p className="max-w-md self-end text-sm leading-6 text-slate-400">From the first WhatsApp enquiry to the final review, every handoff stays visible, thoughtful and on time.</p></div><div className="mt-12 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{features.map(([Icon,title,copy],i)=><article key={title} className={`group rounded-3xl border border-white/10 bg-white/[.035] p-6 transition duration-300 hover:-translate-y-1 hover:border-cyan-300/35 hover:bg-white/[.06] ${i===0?"md:col-span-2 xl:col-span-1":""}`}><span className="grid size-11 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-200"><Icon className="size-5" /></span><h3 className="mt-9 text-lg font-semibold tracking-tight text-white">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-slate-400">{copy}</p><a href="#demo" className="mt-7 inline-flex items-center gap-1 text-xs font-bold text-cyan-300 transition hover:text-cyan-100">Explore capability <ArrowRight className="size-3.5" /></a></article>)}</div></section>

    <DashboardShowcase />

    <section id="workflow" className="mx-auto max-w-7xl px-5 py-24 text-center lg:px-8 lg:py-32"><p className="text-xs font-bold tracking-[.18em] text-cyan-300">THE CONPHIDENT FLOW</p><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-semibold tracking-[-.06em] text-white sm:text-5xl">One patient journey. One source of truth.</h2><div className="mt-14 flex flex-wrap justify-center gap-3">{steps.map((step,index)=><div key={step} className="flex items-center gap-3"><span className="rounded-full border border-white/10 bg-white/[.04] px-4 py-3 text-sm font-semibold text-slate-200"><b className="mr-2 text-cyan-300">{String(index+1).padStart(2,"0")}</b>{step}</span>{index<steps.length-1&&<ArrowRight className="size-4 text-slate-600" />}</div>)}</div></section>

    <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8 lg:pb-32"><div className="grid overflow-hidden rounded-[32px] border border-white/10 bg-[radial-gradient(circle_at_90%_10%,rgba(67,209,204,.18),transparent_28%),linear-gradient(135deg,#0e2632,#101b39)] p-7 md:grid-cols-2 md:p-14"><div><p className="text-xs font-bold tracking-[.18em] text-cyan-200">AI THAT FEELS LIKE A GREAT FRONT DESK</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.06em] text-white">Every patient gets a timely, thoughtful response.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-slate-300">ConphiDent turns WhatsApp into a dependable first line of care—answering common questions, capturing intent and helping patients take the next step.</p><a href={whatsappHref} className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3.5 text-sm font-bold text-slate-950 transition hover:bg-cyan-100">See the AI receptionist <ArrowRight className="size-4" /></a></div><div className="mt-10 self-center rounded-3xl border border-white/10 bg-slate-950/35 p-5 backdrop-blur md:mt-0"><div className="flex items-center gap-3 border-b border-white/10 pb-4"><span className="grid size-9 place-items-center rounded-full bg-cyan-300 text-slate-950"><Bot className="size-4" /></span><div><b className="block text-sm">ConphiDent Assistant</b><small className="text-xs text-emerald-300">Online now</small></div></div><div className="mt-5 max-w-[80%] rounded-2xl rounded-tl-sm bg-white p-3 text-sm text-slate-800">Hi! I&apos;d like to book a cleaning.</div><div className="ml-auto mt-3 max-w-[80%] rounded-2xl rounded-tr-sm bg-cyan-300 p-3 text-sm font-medium text-slate-950">Of course. Which day works best for you?</div><div className="mt-3 max-w-[80%] rounded-2xl rounded-tl-sm bg-white p-3 text-sm text-slate-800">Saturday morning.</div><p className="mt-5 text-xs text-cyan-200">● Finding available slots…</p></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold tracking-[.18em] text-cyan-300">BUILT TO EARN TRUST</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.06em] text-white">A platform teams are proud to run on.</h2></div><div className="grid gap-3 md:grid-cols-2">{[["“", "The clarity alone changes how the whole clinic feels. Our team knows what to do next."],["“", "It turns WhatsApp from a noisy inbox into an organised patient experience."]].map(([quote,text],i)=><figure key={i} className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><span className="text-4xl text-cyan-300">{quote}</span><blockquote className="mt-2 text-lg leading-7 text-slate-200">{text}</blockquote><figcaption className="mt-7 text-xs font-semibold text-slate-500">Placeholder testimonial · Clinic owner</figcaption></figure>)}</div></div></section>

    <section id="pricing" className="mx-auto max-w-7xl px-5 pb-24 lg:px-8 lg:pb-32"><div className="rounded-[32px] border border-cyan-200/15 bg-gradient-to-br from-cyan-300/10 to-violet-400/10 p-8 text-center md:p-14"><Crown className="mx-auto size-6 text-cyan-200" /><p className="mt-5 text-xs font-bold tracking-[.18em] text-cyan-200">SIMPLE, HUMAN PRICING</p><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-semibold tracking-[-.06em] text-white">Built around the way your clinic grows.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-slate-300">Every practice needs a considered rollout. We&apos;ll shape the right workspace, team access and automation plan with you.</p><div className="mx-auto mt-9 flex max-w-2xl flex-wrap justify-center gap-x-7 gap-y-3 text-sm text-slate-200"><span><Check className="mr-1 inline size-4 text-cyan-300" /> Guided onboarding</span><span><Check className="mr-1 inline size-4 text-cyan-300" /> Dedicated workspace</span><span><Check className="mr-1 inline size-4 text-cyan-300" /> WhatsApp onboarding</span></div><a href="#demo" className="mt-9 inline-flex items-center gap-2 rounded-full bg-cyan-300 px-5 py-3.5 text-sm font-bold text-slate-950 transition hover:bg-cyan-200">Talk to our team <ArrowRight className="size-4" /></a></div></section>

    <section className="mx-auto max-w-3xl px-5 pb-24 lg:pb-32"><p className="text-center text-xs font-bold tracking-[.18em] text-cyan-300">COMMON QUESTIONS</p><h2 className="mt-4 text-center text-4xl font-semibold tracking-[-.06em] text-white">A clearer way to run your clinic starts here.</h2><div className="mt-10 divide-y divide-white/10">{[["Is ConphiDent built for multi-location clinics?","Yes. Each clinic workspace is isolated, with dedicated people, permissions, configuration and WhatsApp connection."],["Can we use our own WhatsApp number?","Yes. Each clinic can connect its WhatsApp Business account through Meta Embedded Signup."],["How quickly can we go live?","We begin with a guided workflow review, setup and team onboarding tailored to your clinic."]].map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-semibold text-slate-100">{q}<ChevronDown className="size-5 text-slate-500 transition group-open:rotate-180" /></summary><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{a}</p></details>)}</div></section>

    <section id="demo" className="mx-auto max-w-7xl px-5 pb-20 lg:px-8"><div className="grid gap-10 rounded-[32px] border border-white/10 bg-white/[.045] p-7 md:grid-cols-[.8fr_1.2fr] md:p-12"><div><p className="text-xs font-bold tracking-[.18em] text-cyan-300">A BETTER CLINIC DAY STARTS HERE</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.06em] text-white">See what a connected clinic feels like.</h2><p className="mt-5 text-sm leading-7 text-slate-400">Tell us a little about your practice. We&apos;ll prepare a focused demo around the workflows that matter to your team.</p><a href={whatsappHref} className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-emerald-300 hover:text-emerald-200"><MessageCircle className="size-4" /> Prefer WhatsApp? Chat instantly.</a></div><DemoForm /></div></section>
    <footer className="border-t border-white/10"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><Link href="/" className="flex items-center gap-2.5 text-lg font-bold tracking-[-.06em]"><Mark /> Conphi<span className="text-cyan-300">Dent</span></Link><p className="mt-4 max-w-48 text-sm leading-6 text-slate-500">The operating system for confident dental clinics.</p></div><div><b className="text-sm">Platform</b><a href="#platform" className="mt-4 block text-sm text-slate-400 hover:text-white">Capabilities</a><a href="#workflow" className="mt-3 block text-sm text-slate-400 hover:text-white">How it works</a></div><div><b className="text-sm">Company</b><a href="#demo" className="mt-4 block text-sm text-slate-400 hover:text-white">Book a demo</a><Link href="/terms" className="mt-3 block text-sm text-slate-400 hover:text-white">Terms</Link></div><div><b className="text-sm">Get in touch</b><a href={whatsappHref} className="mt-4 block text-sm text-emerald-300 hover:text-emerald-200">Chat on WhatsApp</a><Link href="/login" className="mt-3 block text-sm text-slate-400 hover:text-white">Sign in</Link></div></div><div className="mx-auto max-w-7xl border-t border-white/10 px-5 py-5 text-xs text-slate-600 lg:px-8">© {new Date().getFullYear()} ConphiDent. Built for better clinic days.</div></footer>
    <a aria-label="Chat with ConphiDent on WhatsApp" href={whatsappHref} className="fixed bottom-5 right-5 z-20 grid size-14 place-items-center rounded-full bg-[#25D366] text-white shadow-2xl shadow-emerald-950/50 transition hover:scale-105"><MessageCircle className="size-6" /></a>
  </main>;
}
