import Link from "next/link";
import PageHeader from "@/components/lists/PageHeader";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth";
import { changePasswordAction, logoutAllDevicesAction } from "@/app/login/actions";
import { requestEmailVerificationAction, requestPhoneVerificationAction, verifyEmailAction, verifyPhoneAction } from "./actions";

export default async function SecuritySettingsPage({ searchParams }: { searchParams: Promise<{ error?: string; changed?: string; emailSent?: string; emailVerified?: string; phoneSent?: string; phoneVerified?: string }> }) {
  const user = await requireUser();
  const [params, sessions, events] = await Promise.all([
    searchParams,
    prisma.session.findMany({ where: { userId: user.id, expiresAt: { gt: new Date() } }, select: { id: true, createdAt: true, expiresAt: true }, orderBy: { createdAt: "desc" }, take: 12 }),
    prisma.auditLog.findMany({ where: { clinicId: user.clinicId, userId: user.id, action: { in: ["LOGIN_SUCCEEDED", "PASSWORD_CHANGED", "PASSWORD_RESET_COMPLETED", "SESSIONS_REVOKED"] } }, orderBy: { createdAt: "desc" }, take: 12 }),
  ]);
  return <div className="flex w-full flex-col gap-5"><PageHeader title="Your sign-in" sub="Your password, where you are still signed in, and what has happened on your account. We never keep passwords or codes in this list." actions={<Link href="/dashboard/settings?tab=people" className="inline-flex min-h-11 items-center rounded-control border border-border-strong bg-card px-3.5 text-[length:var(--text-secondary)] font-semibold text-heading hover:bg-muted">Back to Settings</Link>} />
    {params.error && <p className="rounded-control border border-danger-border bg-danger-bg px-3.5 py-3 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-danger">Password could not be changed. Check your current password and use at least 12 characters with upper- and lower-case letters plus a number.</p>}
    {params.changed && <p className="rounded-control border border-success-border bg-success-bg px-3.5 py-3 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-success">Password updated. Other sessions were signed out.</p>}
    {params.emailSent && <p className="rounded-control border border-success-border bg-success-bg px-3.5 py-3 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-success">Verification code sent to your email.</p>}
    {params.emailVerified && <p className="rounded-control border border-success-border bg-success-bg px-3.5 py-3 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-success">Email verified.</p>}
    {params.phoneSent && <p className="rounded-control border border-success-border bg-success-bg px-3.5 py-3 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-success">Verification code sent to your phone.</p>}
    {params.phoneVerified && <p className="rounded-control border border-success-border bg-success-bg px-3.5 py-3 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-success">Phone verified.</p>}
    <section className="rounded-card border border-border bg-card p-5.5 shadow-[var(--shadow)]"><h2 className="text-[length:var(--text-section)] leading-[var(--text-section-lh)] font-semibold text-heading">Verification</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="rounded-control border border-border p-3.5"><p className="font-semibold">Email</p><p className="mt-1 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-text-muted">{user.email} · {user.emailVerifiedAt ? "Verified" : "Not verified"}</p>{user.emailVerifiedAt ? null : <><form action={requestEmailVerificationAction} className="mt-3"><button className="text-sm font-semibold text-primary hover:underline">Send verification code</button></form><form action={verifyEmailAction} className="mt-3 flex gap-2"><input name="code" inputMode="numeric" maxLength={6} required placeholder="6-digit code" className="min-h-11 min-w-0 flex-1 rounded-control border px-3 text-sm"/><button className="rounded-control bg-primary px-3 text-sm font-semibold text-primary-foreground">Verify</button></form></>}</div><div className="rounded-control border border-border p-3.5"><p className="font-semibold">Phone</p><p className="mt-1 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-text-muted">{user.phoneVerifiedAt ? `${user.phone} · Verified` : "Not verified"}</p><form action={requestPhoneVerificationAction} className="mt-3 flex gap-2"><input name="phone" inputMode="tel" defaultValue={user.phone ?? ""} required placeholder="+919876543210" className="min-h-11 min-w-0 flex-1 rounded-control border px-3 text-sm"/><button className="rounded-control border px-3 text-sm font-semibold">Send code</button></form><form action={verifyPhoneAction} className="mt-3 flex gap-2"><input name="phone" inputMode="tel" defaultValue={user.phone ?? ""} required placeholder="Phone" className="min-h-11 min-w-0 flex-1 rounded-control border px-3 text-sm"/><input name="code" inputMode="numeric" maxLength={6} required placeholder="Code" className="min-h-11 w-20 rounded-control border px-3 text-sm"/><button className="rounded-control bg-primary px-3 text-sm font-semibold text-primary-foreground">Verify</button></form></div></div></section>
    <section className="rounded-card border border-border bg-card p-5.5 shadow-[var(--shadow)]"><h2 className="text-[length:var(--text-section)] leading-[var(--text-section-lh)] font-semibold text-heading">Change password</h2><form action={changePasswordAction} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Current password<input name="currentPassword" type="password" autoComplete="current-password" required className="mt-1.5 min-h-11 w-full rounded-control border border-border px-3 font-normal" /></label><label className="text-sm font-semibold">New password<input name="password" type="password" autoComplete="new-password" minLength={12} required className="mt-1.5 min-h-11 w-full rounded-control border border-border px-3 font-normal" /></label><label className="text-sm font-semibold">Confirm new password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} required className="mt-1.5 min-h-11 w-full rounded-control border border-border px-3 font-normal" /></label><p className="text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-text-muted sm:col-span-2">Use 12+ characters with upper- and lower-case letters and a number. Changing your password signs out other devices.</p><button className="min-h-11 w-fit rounded-control bg-primary px-5 font-semibold text-primary-foreground hover:bg-primary-hover">Update password</button></form></section>
    <section className="rounded-card border border-border bg-card p-5.5 shadow-[var(--shadow)]"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-[length:var(--text-section)] leading-[var(--text-section-lh)] font-semibold text-heading">Active sessions</h2><p className="mt-1 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-text-muted">{sessions.length} active session{sessions.length === 1 ? "" : "s"}. Device details will appear here when a session metadata provider is configured.</p></div><form action={logoutAllDevicesAction}><button className="rounded-control border border-danger-border px-4 py-2 text-sm font-semibold text-danger hover:bg-danger-bg">Logout all devices</button></form></div><div className="mt-4 divide-y">{sessions.map((session) => <div key={session.id} className="flex justify-between gap-4 py-3 text-sm"><span>Signed in {session.createdAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</span><span className="text-text-muted">Expires {session.expiresAt.toLocaleDateString("en-IN")}</span></div>)}</div></section>
    <section className="rounded-card border border-border bg-card p-5.5 shadow-[var(--shadow)]"><h2 className="text-[length:var(--text-section)] leading-[var(--text-section-lh)] font-semibold text-heading">Recent security activity</h2>{events.length ? <div className="mt-4 divide-y">{events.map((event) => <div key={event.id} className="flex justify-between gap-4 py-3 text-sm"><span>{event.action.replaceAll("_", " ")}</span><time className="text-text-muted">{event.createdAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</time></div>)}</div> : <p className="mt-3 text-[length:var(--text-body)] leading-[var(--text-body-lh)] text-text-muted">No security activity has been recorded yet.</p>}<Link href="/dashboard/settings" className="mt-5 inline-block text-sm font-semibold text-primary hover:underline">Back to clinic settings</Link></section>
  </div>;
}
