import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth";
import { changePasswordAction, logoutAllDevicesAction } from "@/app/login/actions";
import { requestEmailVerificationAction, requestPhoneVerificationAction, verifyEmailAction, verifyPhoneAction } from "./actions";

export default async function SecuritySettingsPage({ searchParams }: { searchParams: Promise<{ error?: string; changed?: string; emailSent?: string; emailVerified?: string; phoneSent?: string; phoneVerified?: string }> }) {
  const user = await requireUser();
  const [params, sessions, events] = await Promise.all([
    searchParams,
    prisma.session.findMany({ where: { userId: user.id, expiresAt: { gt: new Date() } }, select: { id: true, createdAt: true, expiresAt: true }, orderBy: { createdAt: "desc" }, take: 12 }),
    prisma.auditLog.findMany({ where: { clinicId: user.clinicId, userId: user.id, action: { in: ["LOGIN_SUCCEEDED", "PASSWORD_CHANGED", "PASSWORD_RESET_COMPLETED", "SESSIONS_REVOKED"] } }, orderBy: { createdAt: "desc" }, take: 12 }),
  ]);
  return <div className="mx-auto max-w-4xl space-y-6"><header><p className="text-sm font-bold uppercase tracking-[0.16em] text-sky-700">Account</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Security & sign-in</h1><p className="mt-2 text-muted-foreground">Manage verification, passwords, and active sessions. Security events never contain passwords, tokens, or one-time codes.</p></header>
    {params.error && <p className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">Password could not be changed. Check your current password and use at least 12 characters with upper- and lower-case letters plus a number.</p>}
    {params.changed && <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Password updated. Other sessions were signed out.</p>}
    {params.emailSent && <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Verification code sent to your email.</p>}
    {params.emailVerified && <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Email verified.</p>}
    {params.phoneSent && <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Verification code sent to your phone.</p>}
    {params.phoneVerified && <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Phone verified.</p>}
    <section className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Verification</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="rounded-xl border p-4"><p className="font-semibold">Email</p><p className="mt-1 text-sm text-muted-foreground">{user.email} · {user.emailVerifiedAt ? "Verified" : "Not verified"}</p>{user.emailVerifiedAt ? null : <><form action={requestEmailVerificationAction} className="mt-3"><button className="text-sm font-semibold text-primary hover:underline">Send verification code</button></form><form action={verifyEmailAction} className="mt-3 flex gap-2"><input name="code" inputMode="numeric" maxLength={6} required placeholder="6-digit code" className="h-10 min-w-0 flex-1 rounded-lg border px-3 text-sm"/><button className="rounded-lg bg-slate-900 px-3 text-sm font-semibold text-white">Verify</button></form></>}</div><div className="rounded-xl border p-4"><p className="font-semibold">Phone</p><p className="mt-1 text-sm text-muted-foreground">{user.phoneVerifiedAt ? `${user.phone} · Verified` : "Not verified"}</p><form action={requestPhoneVerificationAction} className="mt-3 flex gap-2"><input name="phone" inputMode="tel" defaultValue={user.phone ?? ""} required placeholder="+919876543210" className="h-10 min-w-0 flex-1 rounded-lg border px-3 text-sm"/><button className="rounded-lg border px-3 text-sm font-semibold">Send code</button></form><form action={verifyPhoneAction} className="mt-3 flex gap-2"><input name="phone" inputMode="tel" defaultValue={user.phone ?? ""} required placeholder="Phone" className="h-10 min-w-0 flex-1 rounded-lg border px-3 text-sm"/><input name="code" inputMode="numeric" maxLength={6} required placeholder="Code" className="h-10 w-20 rounded-lg border px-3 text-sm"/><button className="rounded-lg bg-slate-900 px-3 text-sm font-semibold text-white">Verify</button></form></div></div></section>
    <section className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Change password</h2><form action={changePasswordAction} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Current password<input name="currentPassword" type="password" autoComplete="current-password" required className="mt-1.5 h-11 w-full rounded-xl border px-3 font-normal" /></label><label className="text-sm font-semibold">New password<input name="password" type="password" autoComplete="new-password" minLength={12} required className="mt-1.5 h-11 w-full rounded-xl border px-3 font-normal" /></label><label className="text-sm font-semibold">Confirm new password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} required className="mt-1.5 h-11 w-full rounded-xl border px-3 font-normal" /></label><p className="text-sm text-muted-foreground sm:col-span-2">Use 12+ characters with upper- and lower-case letters and a number. Changing your password signs out other devices.</p><button className="h-11 w-fit rounded-xl bg-slate-900 px-5 font-semibold text-white hover:bg-slate-700">Update password</button></form></section>
    <section className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-bold">Active sessions</h2><p className="mt-1 text-sm text-muted-foreground">{sessions.length} active session{sessions.length === 1 ? "" : "s"}. Device details will appear here when a session metadata provider is configured.</p></div><form action={logoutAllDevicesAction}><button className="rounded-xl border border-rose-200 px-4 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-50">Logout all devices</button></form></div><div className="mt-4 divide-y">{sessions.map((session) => <div key={session.id} className="flex justify-between gap-4 py-3 text-sm"><span>Signed in {session.createdAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</span><span className="text-muted-foreground">Expires {session.expiresAt.toLocaleDateString("en-IN")}</span></div>)}</div></section>
    <section className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Recent security activity</h2>{events.length ? <div className="mt-4 divide-y">{events.map((event) => <div key={event.id} className="flex justify-between gap-4 py-3 text-sm"><span>{event.action.replaceAll("_", " ")}</span><time className="text-muted-foreground">{event.createdAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</time></div>)}</div> : <p className="mt-3 text-sm text-muted-foreground">No security activity has been recorded yet.</p>}<Link href="/dashboard/settings" className="mt-5 inline-block text-sm font-semibold text-primary hover:underline">Back to clinic settings</Link></section>
  </div>;
}
