"use client";
import { ChevronDown, LogOut, Search, Settings, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { logoutAction } from "@/app/dashboard/account-actions";
import NotificationBell, { type DashboardNotification } from "@/components/NotificationBell";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Input } from "@/components/ui/input";

export default function Navbar({ user, notifications = [] }: { user: { fullName: string; role: string; clinicName: string; clinicAddress: string }; notifications?: DashboardNotification[] }) {
  const initials = user.fullName.split(" ").map(x => x[0]).join("").slice(0, 2).toUpperCase(); const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-10 flex h-20 items-center justify-between border-b border-border/70 bg-background/90 py-0 pl-24 pr-6 backdrop-blur-xl lg:pr-10"><div className="min-w-0"><p className="truncate text-xs font-semibold uppercase tracking-[.16em] text-primary">{user.clinicName}</p><h2 className="mt-1 truncate text-sm font-medium text-slate-700">{user.clinicAddress}</h2></div><div className="flex shrink-0 items-center gap-3"><form action="/dashboard/search" className="relative hidden md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input name="q" placeholder="Search patients, appointments, invoices…" className="h-10 w-72 rounded-xl border-border bg-white pl-10 shadow-sm"/></form><NotificationBell items={notifications}/><div className="relative"><button type="button" onClick={() => setOpen(x => !x)} className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-muted"><div className="hidden text-right text-xs text-slate-500 sm:block"><p className="font-semibold text-slate-800">{user.fullName}</p><p>{user.role.toLowerCase()}</p></div><Avatar className="size-10 shadow-sm"><AvatarFallback className="bg-primary font-semibold text-primary-foreground">{initials}</AvatarFallback></Avatar><ChevronDown className="size-4 text-slate-500"/></button>{open && <div className="absolute right-0 top-14 z-50 w-60 rounded-2xl border bg-white p-2 shadow-xl"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Account</p><Link href="/dashboard/settings" onClick={() => setOpen(false)} className="flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold hover:bg-slate-50"><Settings className="size-4"/>Profile & clinic details</Link><Link href="/dashboard/settings/whatsapp" onClick={() => setOpen(false)} className="flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold hover:bg-slate-50"><ShieldCheck className="size-4"/>Notifications & WhatsApp</Link><p className="px-3 py-2 text-xs text-slate-500">Switch account activates when another clinic membership is added.</p><form action={logoutAction}><button className="flex w-full items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-50"><LogOut className="size-4"/>Logout</button></form></div>}</div></div></header>;
}
