"use client";

import { useState } from "react";
import { Activity, CalendarDays, MessageCircle, UsersRound } from "lucide-react";

const views = {
  Overview: { icon: Activity, eyebrow: "Command centre", title: "A live view of every moving part.", copy: "See care, team capacity and revenue signals without changing context.", metric: "₹1.48L", label: "Today’s collections", bars: [42, 61, 48, 78, 64, 91, 76] },
  Patients: { icon: UsersRound, eyebrow: "Patient intelligence", title: "Patient context at the moment it matters.", copy: "Every conversation, treatment plan and next action stays connected.", metric: "1,284", label: "Active patient records", bars: [38, 52, 73, 58, 84, 67, 95] },
  Schedule: { icon: CalendarDays, eyebrow: "Operational rhythm", title: "Make a full day feel effortless.", copy: "Balance chairs, clinicians and patient expectations in one calm schedule.", metric: "24", label: "Appointments today", bars: [65, 42, 76, 55, 89, 68, 82] },
  WhatsApp: { icon: MessageCircle, eyebrow: "Responsive care", title: "Turn every enquiry into momentum.", copy: "AI-assisted conversations are organised, timely and ready for your team.", metric: "87%", label: "First-response rate", bars: [35, 61, 56, 82, 72, 92, 88] },
};

export default function DashboardShowcase() {
  const [active, setActive] = useState<keyof typeof views>("Overview");
  const view = views[active]; const Icon = view.icon;
  return <section className="border-y border-white/8 bg-[#091920] py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.72fr_1.28fr] lg:px-8"><div className="self-center"><p className="text-xs font-bold tracking-[.18em] text-cyan-300">DESIGNED FOR THE REAL DAY</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.06em] text-white sm:text-5xl">Less switching. More certainty.</h2><p className="mt-5 max-w-md text-sm leading-7 text-slate-400">A unified system gives every role the same source of truth—without forcing every person into the same view.</p><div className="mt-8 grid gap-2">{(Object.keys(views) as Array<keyof typeof views>).map((key)=>{const TabIcon=views[key].icon;return <button type="button" key={key} onClick={()=>setActive(key)} className={`flex items-center gap-3 rounded-2xl border px-4 py-3 text-left text-sm font-semibold transition ${active===key?"border-cyan-300/35 bg-cyan-300/10 text-cyan-100":"border-transparent text-slate-400 hover:bg-white/[.04] hover:text-white"}`}><TabIcon className="size-4" />{key}</button>})}</div></div><div className="rounded-[28px] border border-white/10 bg-slate-950/40 p-3 shadow-2xl shadow-black/20"><div className="rounded-[21px] border border-white/10 bg-[#10242d] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-cyan-300">{view.eyebrow}</p><h3 className="mt-1 text-xl font-semibold text-white">{view.title}</h3></div><span className="grid size-10 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-200"><Icon className="size-5" /></span></div><p className="mt-3 max-w-lg text-sm leading-6 text-slate-400">{view.copy}</p><div className="mt-8 grid gap-3 sm:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><span className="text-xs text-slate-400">Performance over 7 days</span><div className="mt-8 flex h-36 items-end gap-2">{view.bars.map((h,i)=><i key={i} style={{height:`${h}%`}} className="block flex-1 rounded-t-lg bg-gradient-to-t from-cyan-500 to-blue-300" />)}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><span className="text-xs text-slate-400">{view.label}</span><b className="mt-5 block text-3xl tracking-tight text-white">{view.metric}</b><span className="mt-1 block text-xs font-semibold text-emerald-300">↑ Performing well</span></div></div></div></div></div></section>;
}
