"use client";

import Image from "next/image";
import { useState } from "react";

const panels = [
  { id: "dashboard", label: "Dashboard", title: "See today’s clinic priorities in one command centre.", problem: "Teams lose time when the day’s appointments, follow-ups and financial signals live in separate places.", visible: "Appointments, patient activity, clinical overview, collections and front-desk priorities.", why: "Everyone starts from the same operating picture.", image: "/product/dashboard/dashboard-demo.png", width: 950, height: 540 },
  { id: "patients", label: "Patients", title: "Keep the complete patient context together.", problem: "Patient details, visits and care records become difficult to follow across disconnected tools.", visible: "Patient details, visit dates, clinical workspace, plans, invoices and action shortcuts.", why: "The record becomes the centre of the clinic journey.", image: "/product/patients/patient-profile-demo.png", width: 1171, height: 1180 },
  { id: "appointments", label: "Appointments", title: "Turn scheduling into a connected clinic workflow.", problem: "A calendar alone cannot carry the reason, patient context and next communication.", visible: "Clinic schedule, visit times, appointment status and patient-linked booking details.", why: "The front desk coordinates capacity with less switching.", image: "/product/appointments/calendar-demo.png", width: 1171, height: 1144 },
  { id: "clinical", label: "Clinical", title: "Give every clinical decision its context.", problem: "Tooth findings, notes and plans should not be scattered across separate records.", visible: "Visit-linked dental chart, findings, clinical notes and patient summary access.", why: "Care decisions stay traceable and connected.", image: "/product/clinical/clinical-workspace-demo.png", width: 1171, height: 1180 },
  { id: "billing", label: "Billing", title: "Connect care delivered to money received.", problem: "Disconnected billing makes balances harder to explain and follow up.", visible: "Invoice line items, payment capture, receipt actions and outstanding balance.", why: "Finance context stays attached to the patient.", image: "/product/billing/billing-invoice-demo.png", width: 1171, height: 1180 },
  { id: "whatsapp", label: "WhatsApp", title: "Turn communication into accountable clinic work.", problem: "Messages and reminders are unreliable when nobody can see delivery or ownership.", visible: "Scheduled queue, delivery status, failures and outbound history.", why: "Patient communication becomes observable and actionable.", image: "/product/whatsapp/whatsapp-operations-demo.png", width: 1171, height: 1001 },
  { id: "laboratory", label: "Laboratory", title: "Track lab work inside the patient journey.", problem: "Manual lab coordination makes due dates, rework and case ownership hard to follow.", visible: "Case creation, patient, lab, material, shade, due date, priority and status metrics.", why: "The clinic sees what is due before it becomes delayed.", image: "/product/laboratory/laboratory-management-demo.png", width: 1171, height: 1180 },
  { id: "inventory", label: "Inventory", title: "Make stock movement operationally visible.", problem: "Expiry, low stock and purchase needs become urgent when tracked manually.", visible: "Inventory operations, stock movement and purchasing controls.", why: "Teams can act before essential supplies run out.", image: "/product/inventory/operations-demo.png", width: 1171, height: 1180 },
  { id: "reports", label: "Reports", title: "Turn clinic activity into decisions.", problem: "Static spreadsheets make it difficult to spot what needs attention now.", visible: "Appointment, revenue, follow-up and performance reporting from connected records.", why: "Clinic leaders can move from reporting to action.", image: "/product/reports/reports-demo.png", width: 1171, height: 1180 },
];

export default function PlatformExplorer() {
  const [active, setActive] = useState(0);
  const panel = panels[active];
  return <section className="mk-platform" id="platform-overview"><div className="cf-wrap"><div className="mk-section-heading"><p className="mk-kicker">Platform overview</p><h2>Explore the connected clinic workspace.</h2><p>Every preview below comes from the real ConphiDent product and uses sanitized demonstration data. Select an area to see the exact workflow and the operational problem it addresses.</p></div><div className="mk-platform-tabs" role="tablist" aria-label="Product areas">{panels.map((item, index) => <button key={item.id} id={`tab-${item.id}`} role="tab" aria-selected={active === index} aria-controls={`panel-${item.id}`} onClick={() => setActive(index)}>{item.label}</button>)}</div><div className="mk-platform-panel" id={`panel-${panel.id}`} role="tabpanel" aria-labelledby={`tab-${panel.id}`}><div className="mk-platform-copy"><p className="mk-kicker">{panel.label}</p><h3>{panel.title}</h3><dl><div><dt>Problem solved</dt><dd>{panel.problem}</dd></div><div><dt>What you can see</dt><dd>{panel.visible}</dd></div><div><dt>Why it matters</dt><dd>{panel.why}</dd></div></dl></div><figure className="mk-product-frame mk-platform-frame"><div className="mk-window-bar"><i/><i/><i/><span>ConphiDent · {panel.label}</span></div><Image src={panel.image} alt={`${panel.label} workspace in ConphiDent using fictional demonstration data`} width={panel.width} height={panel.height} sizes="(max-width: 900px) 92vw, 58vw"/><figcaption className="mk-screen-caption"><b>What to notice:</b> {panel.visible}</figcaption><span className="mk-callout-dot" aria-hidden="true">01</span></figure></div></div></section>;
}
