import Link from "next/link";
import { resetPasswordAction } from "@/app/login/actions";
import { PASSWORD_MIN_LENGTH } from "@/lib/auth";
import { PLATFORM_NAME } from "@/lib/platform";

export default async function ResetPasswordPage({ searchParams }: { searchParams: Promise<{ token?: string; error?: string }> }) {
  const { token, error } = await searchParams;
  if (!token) return <main className="login-screen grid min-h-screen place-items-center bg-slate-50 p-5"><section className="rounded-3xl border bg-white p-8 text-center"><h1 className="text-2xl font-bold">Invalid reset link</h1><Link href="/forgot-password" className="mt-5 inline-block font-semibold text-cyan-700 hover:underline">Request a new link</Link></section></main>;
  return <main className="login-screen grid min-h-screen place-items-center bg-slate-50 p-5"><section className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl shadow-slate-900/10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-700">{PLATFORM_NAME}</p><h1 className="mt-3 text-3xl font-bold text-slate-950">Choose a new password</h1><p className="mt-2 text-sm text-slate-500">Use at least {PASSWORD_MIN_LENGTH} characters with upper- and lower-case letters and a number. You will need to sign in again on other devices.</p>{error && <p className="mt-4 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">Passwords must match and use at least {PASSWORD_MIN_LENGTH} characters with upper- and lower-case letters and a number.</p>}<form action={resetPasswordAction} className="mt-7 space-y-5"><input type="hidden" name="token" value={token} /><label className="block text-sm font-semibold text-slate-800">New password<input name="password" type="password" required minLength={PASSWORD_MIN_LENGTH} autoComplete="new-password" className="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-cyan-600 focus:ring-4 focus:ring-cyan-100" /></label><label className="block text-sm font-semibold text-slate-800">Confirm new password<input name="confirmPassword" type="password" required minLength={PASSWORD_MIN_LENGTH} autoComplete="new-password" className="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-cyan-600 focus:ring-4 focus:ring-cyan-100" /></label><button className="h-12 w-full rounded-xl bg-cyan-700 font-semibold text-white hover:bg-cyan-800">Save new password</button></form><Link href="/login" className="mt-7 inline-block text-sm font-semibold text-cyan-700 hover:underline">Back to sign in</Link></section></main>;
}
