import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requirePlatformPermission } from "@/lib/platform";

const money = (value: number, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(value / 100);
const date = (value: Date | null) => value ? value.toLocaleDateString("en-IN", { dateStyle: "medium" }) : "Not scheduled";

export default async function BillingPage({ searchParams }: { searchParams: Promise<{ status?: string; plan?: string }> }) {
  await requirePlatformPermission("billing.read");
  const p = await searchParams; const status = p.status || ""; const planCode = p.plan || "";
  const where = { AND: [...(status ? [{ status }] : []), ...(planCode ? [{ plan: { code: planCode } }] : [])] };
  const now = new Date(); const renewalWindowEnd = new Date(now); renewalWindowEnd.setDate(renewalWindowEnd.getDate() + 30);
  const [plans, subscriptions, allSubscriptions, renewals, clinicPayments] = await Promise.all([
    prisma.subscriptionPlan.findMany({ orderBy: [{ active: "desc" }, { name: "asc" }] }),
    prisma.tenantSubscription.findMany({ where, include: { clinic: { select: { id: true, name: true, brandName: true, status: true } }, plan: true }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.tenantSubscription.findMany({ select: { status: true, price: true, currency: true, billingCycle: true, planId: true } }),
    prisma.tenantSubscription.findMany({ where: { renewsAt: { gte: now, lte: renewalWindowEnd }, status: { in: ["ACTIVE", "TRIAL"] } }, include: { clinic: { select: { name: true, brandName: true } }, plan: { select: { name: true } } }, orderBy: { renewsAt: "asc" }, take: 20 }),
    prisma.payment.count(),
  ]);
  const recurring = allSubscriptions.filter((s) => s.status === "ACTIVE" && s.price !== null);
  const mrr = recurring.reduce((sum, s) => sum + (s.billingCycle === "YEARLY" ? Math.round(s.price! / 12) : s.billingCycle === "QUARTERLY" ? Math.round(s.price! / 3) : s.price!), 0);
  const counts = (value: string) => allSubscriptions.filter((s) => s.status === value).length;
  return <main className="space-y-6 pb-12"><header><p className="text-sm font-bold uppercase tracking-[.16em] text-[#176b87]">Billing</p><h1 className="mt-1 text-3xl font-bold">Revenue Command Center</h1><p className="mt-2 text-sm text-muted-foreground">SaaS revenue uses only tenant subscription prices. Patient invoices and payments are clinic operational data, not platform revenue.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="MRR" value={money(mrr)} note="Normalized from active subscription prices"/><Metric label="ARR" value={money(mrr * 12)} note="Annualized MRR, not recognized revenue"/><Metric label="Active / trial" value={`${counts("ACTIVE")} / ${counts("TRIAL")}`}/><Metric label="Past due / cancelled" value={`${counts("PAST_DUE")} / ${counts("CANCELLED")}`}/></section>
    <form className="flex flex-wrap gap-3 rounded-xl border bg-white p-4"><select name="status" defaultValue={status} className="h-10 rounded-lg border px-3"><option value="">All subscription states</option>{["TRIAL", "ACTIVE", "PAST_DUE", "SUSPENDED", "CANCELLED"].map((v) => <option key={v}>{v}</option>)}</select><select name="plan" defaultValue={planCode} className="h-10 rounded-lg border px-3"><option value="">All plans</option>{plans.map((plan) => <option key={plan.id} value={plan.code}>{plan.name}</option>)}</select><button className="rounded-lg bg-[#123b5d] px-4 text-sm font-semibold text-white">Apply</button></form>
    <section className="grid gap-6 xl:grid-cols-3"><Panel title="Upcoming renewals"><div className="divide-y">{renewals.map((item) => <div key={item.id} className="py-3 text-sm"><p className="font-semibold">{item.clinic.brandName || item.clinic.name}</p><p className="text-xs text-slate-500">{item.plan?.name || "Custom"} · {money(item.price || 0, item.currency)} · {date(item.renewsAt)}</p></div>)}{!renewals.length && <Empty text="No renewals are scheduled in the next 30 days."/>}</div></Panel><Panel title="Revenue data boundary"><p className="text-sm text-slate-600">No payment-provider integration is installed. The {clinicPayments.toLocaleString()} stored payment record(s) are clinic-to-patient collections and are excluded from SaaS MRR, revenue, failed-payment, and churn calculations.</p><p className="mt-3 text-xs text-slate-500">Add a dedicated provider-backed platform billing ledger before enabling payment reconciliation, invoices, retries, or tax reporting here.</p></Panel><Panel title="Plan management"><p className="text-sm text-slate-600">Plans are managed through the existing Control Center plan editor. Deactivation preserves historical tenant plan relationships.</p><Link className="mt-4 inline-block text-sm font-semibold text-[#176b87]" href="/platform">Open plan editor</Link></Panel></section>
    <Panel title="Subscriptions"><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr><th>Clinic</th><th>Plan</th><th>State</th><th>Cycle</th><th>Amount</th><th>Trial ends</th><th>Renews</th><th>Updated</th></tr></thead><tbody>{subscriptions.map((s) => <tr key={s.id} className="border-t"><td className="py-3"><Link className="font-semibold text-[#176b87]" href={`/platform/clinics/${s.clinicId}`}>{s.clinic.brandName || s.clinic.name}</Link></td><td>{s.plan?.name || "Custom"}</td><td>{s.status}</td><td>{s.billingCycle}</td><td>{s.price === null ? "Not set" : money(s.price, s.currency)}</td><td>{date(s.trialEndsAt)}</td><td>{date(s.renewsAt)}</td><td>{date(s.updatedAt)}</td></tr>)}{!subscriptions.length && <tr><td colSpan={8} className="py-6 text-slate-500">No subscriptions match this filter.</td></tr>}</tbody></table></div></Panel>
    <p className="text-xs text-slate-500">Revenue metrics that require provider settlement, payment status, tax, discounts, retry history, expansion/contraction, churn, or trial conversion are intentionally unavailable because no platform billing provider or ledger exists in the current architecture.</p>
  </main>;
}
function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) { return <article className="rounded-xl border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p>{note && <p className="mt-1 text-xs text-slate-500">{note}</p>}</article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">{title}</h2><div className="mt-3">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <p className="py-3 text-sm text-slate-500">{text}</p>; }
