import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, ClipboardPlus, FlaskConical, MessageCircle, Package, ReceiptText, UsersRound } from "lucide-react";
import MarketingMotion from "@/components/marketing/MarketingMotion";
import PublicShell from "@/components/marketing/PublicShell";

export const metadata: Metadata = { title: "Capabilities", description: "Explore patient, appointment, clinical, financial, WhatsApp, laboratory, inventory and reporting workflows in ConphiDent.", alternates: { canonical: "/features" } };
const groups = [["Patient experience", UsersRound, ["Patient profiles and intake", "Appointment history and connected context", "Lead conversion and follow-up queues", "Patient-linked WhatsApp actions"]], ["Clinical care", ClipboardPlus, ["Dental chart and odontogram", "Clinical records and case-paper workflow", "Treatment plans", "Prescriptions"]], ["Finance", ReceiptText, ["Patient-linked invoices", "Payment recording", "Receipt and transaction history", "Outstanding balance visibility"]], ["Communication", MessageCircle, ["WhatsApp conversations", "Appointment reminders", "Scheduled message operations", "Delivery and failure visibility"]], ["Laboratory", FlaskConical, ["Patient-linked lab cases", "Due dates and priority", "Status timeline", "Rework tracking"]], ["Inventory", Package, ["Inventory items", "Stock movement", "Expiry and low-stock awareness", "Purchase orders and vendors"]], ["Reporting", BarChart3, ["Command-centre visibility", "Appointment and financial reporting", "Lead and follow-up analytics", "Operational exports"]]] as const;
export default function Features() { return <PublicShell><MarketingMotion/><section className="mk-page-hero"><div className="cf-wrap" data-reveal><p className="mk-kicker">Verified product capabilities</p><h1>The systems a modern dental clinic needs—connected.</h1><p>Every capability below is grounded in the existing ConphiDent product. No invented features, certifications or performance claims.</p></div></section><section className="mk-capabilities"><div className="cf-wrap mk-capability-grid">{groups.map(([title, Icon, items], index) => <article key={title} data-reveal><span><Icon/></span><small>0{index + 1}</small><h2>{title}</h2><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></section><section className="mk-final"><div className="cf-wrap" data-reveal><h2>See how these capabilities work as one clinic journey.</h2><div className="mk-actions"><Link href="/product" className="mk-button">Explore the platform <ArrowRight/></Link><Link href="/demo" className="mk-text-link">Book a demo <ArrowRight/></Link></div></div></section></PublicShell>; }
