export const dynamic = "force-dynamic";

import { AlertTriangle, CalendarClock, PackageCheck, Plus, TrendingDown } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import DeleteSubmitButton from "@/components/dashboard/DeleteSubmitButton";
import PendingSubmitButton from "@/components/dashboard/PendingSubmitButton";
import { deleteInventoryItemAction } from "@/app/dashboard/delete-actions";
import { addInventoryItemAction, adjustInventoryAction, createPurchaseOrderAction, receivePurchaseOrderItemAction, recordInventoryUsageAction } from "./actions";

export default async function OperationsPage() {
  const user = await requireUser();
  const [items, patients, treatmentPlans, movements, purchaseOrders] = await Promise.all([
    prisma.inventoryItem.findMany({ where: { clinicId: user.clinicId, active: true }, orderBy: [{ quantity: "asc" }, { name: "asc" }] }),
    prisma.patient.findMany({ where: { clinicId: user.clinicId }, select: { id: true, fullName: true }, orderBy: { fullName: "asc" }, take: 100 }),
    prisma.treatmentPlan.findMany({ where: { patient: { clinicId: user.clinicId } }, select: { id: true, title: true }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.inventoryMovement.findMany({ where: { clinicId: user.clinicId }, include: { inventoryItem: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 8 }),
    prisma.purchaseOrder.findMany({ where: { clinicId: user.clinicId }, include: { items: { include: { inventoryItem: { select: { name: true } } } } }, orderBy: { createdAt: "desc" }, take: 6 }),
  ]);
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const lowStock = items.filter((item) => item.quantity <= item.reorderLevel);
  const expiringSoon = items.filter((item) => item.expiryDate && item.expiryDate >= today && item.expiryDate <= new Date(today.getTime() + 90 * 86400000));
  const totalValue = items.reduce((sum, item) => sum + item.quantity * (item.costPerUnit || 0), 0);
  const cards = [["Inventory value", `₹${totalValue.toLocaleString("en-IN")}`, PackageCheck, "text-cyan-700"], ["Low stock", lowStock.length, AlertTriangle, "text-amber-700"], ["Expiring in 90 days", expiringSoon.length, CalendarClock, "text-orange-700"], ["Out of stock", items.filter(x => x.quantity === 0).length, TrendingDown, "text-rose-700"]] as const;
  return <div className="dashboard-list-page mx-auto max-w-7xl space-y-6">
    <header><p className="text-sm font-semibold uppercase tracking-[.16em] text-primary">Clinic inventory</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Inventory operations</h1><p className="mt-2 text-muted-foreground">Manage stock, consumption, expiry exposure and purchase orders in one auditable workspace.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <article key={label} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><Icon className={`size-6 ${color}`} /></div></article>)}</section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-2"><Plus className="size-5 text-primary"/><h2 className="text-lg font-bold">Add or update inventory</h2></div><form action={addInventoryItemAction} className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><input name="name" required placeholder="Item name" className="h-11 rounded-xl border px-3"/><input name="category" placeholder="Category" className="h-11 rounded-xl border px-3"/><input name="quantity" type="number" min="0" defaultValue="0" placeholder="Current quantity" className="h-11 rounded-xl border px-3"/><input name="reorderLevel" type="number" min="0" defaultValue="0" placeholder="Minimum quantity" className="h-11 rounded-xl border px-3"/><input name="unit" defaultValue="units" placeholder="Unit" className="h-11 rounded-xl border px-3"/><input name="costPerUnit" type="number" min="0" placeholder="Cost per unit (₹)" className="h-11 rounded-xl border px-3"/><input name="supplier" placeholder="Vendor / supplier" className="h-11 rounded-xl border px-3"/><input name="batchNumber" placeholder="Batch number" className="h-11 rounded-xl border px-3"/><input name="expiryDate" type="date" className="h-11 rounded-xl border px-3"/><PendingSubmitButton label="Save inventory item" pendingLabel="Saving..." className="h-11 rounded-xl bg-primary px-4 font-semibold text-primary-foreground sm:col-span-2 lg:col-span-3"/></form></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-lg font-bold">Stock levels</h2><p className="mt-1 text-sm text-muted-foreground">Items at or below their minimum quantity are highlighted.</p></div><div className="divide-y">{items.map(item => <article key={item.id} className="flex flex-col gap-4 px-6 py-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex gap-2"><p className="font-semibold">{item.name}</p>{item.quantity <= item.reorderLevel && <span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800">Reorder</span>}</div><p className="mt-1 text-sm text-muted-foreground">{item.category} · {item.quantity} {item.unit} available · reorder at {item.reorderLevel}</p><p className="mt-1 text-xs text-muted-foreground">{item.supplier || "No vendor"}{item.batchNumber ? ` · Batch ${item.batchNumber}` : ""}{item.expiryDate ? ` · Expires ${item.expiryDate.toLocaleDateString("en-IN")}` : ""}</p></div><div className="flex gap-2"><form action={adjustInventoryAction} className="flex gap-2"><input type="hidden" name="id" value={item.id}/><input name="adjustment" type="number" required placeholder="+ / - quantity" className="h-10 w-32 rounded-xl border px-3 text-sm"/><PendingSubmitButton label="Adjust" pendingLabel="Saving..." className="h-10 rounded-xl border px-3 text-sm font-semibold"/></form><form action={deleteInventoryItemAction}><input type="hidden" name="id" value={item.id}/><DeleteSubmitButton confirmMessage={`Delete inventory item ${item.name}?`}/></form></div></article>)}{!items.length && <p className="px-6 py-12 text-center text-sm text-muted-foreground">No inventory items added yet.</p>}</div></section>
    <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h2 className="text-lg font-bold">Record consumption</h2><form action={recordInventoryUsageAction} className="mt-5 grid gap-3 sm:grid-cols-2"><select name="id" required className="h-11 rounded-xl border bg-card px-3"><option value="">Select item</option>{items.map(x=><option key={x.id} value={x.id}>{x.name} ({x.quantity} {x.unit})</option>)}</select><input name="quantity" required type="number" min="1" placeholder="Quantity used" className="h-11 rounded-xl border px-3"/><select name="patientId" className="h-11 rounded-xl border bg-card px-3"><option value="">Patient (optional)</option>{patients.map(x=><option key={x.id} value={x.id}>{x.fullName}</option>)}</select><select name="treatmentPlanId" className="h-11 rounded-xl border bg-card px-3"><option value="">Treatment plan (optional)</option>{treatmentPlans.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><input name="notes" placeholder="Usage note" className="h-11 rounded-xl border px-3 sm:col-span-2"/><PendingSubmitButton label="Record usage" pendingLabel="Recording..." className="h-11 rounded-xl bg-slate-900 px-4 font-semibold text-white sm:col-span-2"/></form></article><article className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h2 className="text-lg font-bold">Create purchase order</h2><form action={createPurchaseOrderAction} className="mt-5 grid gap-3 sm:grid-cols-2"><select name="inventoryItemId" required className="h-11 rounded-xl border bg-card px-3"><option value="">Select item</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="quantity" required type="number" min="1" placeholder="Order quantity" className="h-11 rounded-xl border px-3"/><input name="supplier" required placeholder="Supplier" className="h-11 rounded-xl border px-3"/><input name="notes" placeholder="Reference / note" className="h-11 rounded-xl border px-3"/><PendingSubmitButton label="Create purchase order" pendingLabel="Creating..." className="h-11 rounded-xl bg-primary px-4 font-semibold text-primary-foreground sm:col-span-2"/></form></article></section>
    <section className="grid gap-5 xl:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-lg font-bold">Recent stock movement</h2></div><div className="divide-y">{movements.map(x=><div key={x.id} className="flex justify-between px-6 py-3 text-sm"><div><p className="font-semibold">{x.inventoryItem.name}</p><p className="text-muted-foreground">{x.type.replaceAll("_", " ")} · {x.recordedBy || "Staff"}</p></div><p className={x.quantityChange < 0 ? "font-bold text-rose-700" : "font-bold text-emerald-700"}>{x.quantityChange > 0 ? "+" : ""}{x.quantityChange}</p></div>)}</div></article><article className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-lg font-bold">Recent purchase orders</h2></div><div className="divide-y">{purchaseOrders.map(x=><div key={x.id} className="px-6 py-3 text-sm"><p className="font-semibold">{x.supplier}</p><p className="text-muted-foreground">{x.items.map(i=>`${i.inventoryItem.name} × ${i.quantity}`).join(", ")}</p></div>)}</div></article></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-lg font-bold">Purchase order receiving</h2><p className="mt-1 text-sm text-muted-foreground">Record actual deliveries. Every receipt updates stock through the ledger and supports partial receiving.</p></div><div className="divide-y">{purchaseOrders.map(order => <div key={order.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{order.supplier}</p><span className="rounded-full bg-muted px-2 py-1 text-xs font-semibold">{order.status.replaceAll("_", " ")}</span></div><div className="mt-3 grid gap-2">{order.items.map(item => <form key={item.id} action={receivePurchaseOrderItemAction} className="flex flex-wrap items-center gap-2 rounded-xl bg-muted/40 p-3 text-sm"><input type="hidden" name="purchaseOrderItemId" value={item.id}/><span className="min-w-40 flex-1 font-medium">{item.inventoryItem.name}</span><span className="text-muted-foreground">Ordered {item.quantity} · Received {item.receivedQuantity}</span>{item.receivedQuantity < item.quantity && <><input required name="receivedQuantity" type="number" min="1" max={item.quantity - item.receivedQuantity} placeholder="Qty received" className="h-9 w-28 rounded-lg border bg-white px-2 text-sm"/><button className="h-9 rounded-lg bg-primary px-3 text-sm font-semibold text-primary-foreground">Receive</button></>}</form>)}</div></div>)}{!purchaseOrders.length && <p className="p-6 text-sm text-muted-foreground">No purchase orders yet.</p>}</div></section>
  </div>;
}
