import { prisma } from "@/lib/prisma";
import { PLATFORM_PERMISSIONS, PLATFORM_ROLES, hasPlatformPermission, platformRoleFor, requirePlatformPermission } from "@/lib/platform";
import { revokeUserSessionsAction, setPlatformAdminRoleAction, updateClinicUserAction } from "./actions";

export default async function UsersPage({ searchParams }: { searchParams: Promise<{ q?: string; clinicId?: string; role?: string }> }) {
  const admin = await requirePlatformPermission("user.read"); const p = await searchParams; const q = p.q?.trim().slice(0, 80) || ""; const clinicId = Number(p.clinicId) || undefined;
  const canManagePlatformAdmins = hasPlatformPermission(admin, "admins.manage");
  const canManageClinicUsers = hasPlatformPermission(admin, "user.manage");
  const [clinics, users, admins] = await Promise.all([
    prisma.clinic.findMany({ select: { id: true, name: true, brandName: true }, orderBy: { name: "asc" } }),
    prisma.user.findMany({ where: { platformAdmin: false, ...(clinicId ? { clinicId } : {}), ...(q ? { OR: [{ fullName: { contains: q, mode: "insensitive" } }, { email: { contains: q, mode: "insensitive" } }] } : {}) }, select: { id: true, clinicId: true, fullName: true, email: true, role: true, active: true, createdAt: true, lastLoginAt: true, clinic: { select: { name: true, brandName: true } } }, orderBy: { createdAt: "desc" }, take: 200 }),
    prisma.user.findMany({ where: { platformAdmin: true }, select: { id: true, clinicId: true, fullName: true, email: true, active: true, platformRole: true, lastLoginAt: true, sessions: { select: { id: true, createdAt: true, expiresAt: true } }, clinic: { select: { name: true, brandName: true } } }, orderBy: { updatedAt: "desc" } }),
  ]);
  return <main className="space-y-6 pb-12"><header><p className="platform-eyebrow">Users & security</p><h1 className="mt-1 text-3xl font-bold">Identity and access</h1><p className="mt-2 text-sm text-muted-foreground">Platform roles are separate from clinic roles. Passwords, password hashes, and reset tokens are never displayed.</p></header>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Platform admins</h2><div className="mt-3 divide-y">{admins.map((user) => <div key={user.id} className={`grid gap-3 py-3 ${canManagePlatformAdmins ? "lg:grid-cols-[1fr_220px_auto]" : "lg:grid-cols-[1fr_auto]"}`}><div><p className="font-semibold">{user.fullName} · {platformRoleFor(user)}</p><p className="text-xs text-text-muted">{user.email} · {user.clinic.brandName || user.clinic.name} · last login {user.lastLoginAt?.toLocaleDateString("en-IN") || "never"} · {user.sessions.length} session(s)</p></div>{canManagePlatformAdmins ? <><form action={setPlatformAdminRoleAction} className="flex gap-2"><input type="hidden" name="userId" value={user.id}/><select name="platformRole" defaultValue={platformRoleFor(user)} className="h-9 rounded border px-2">{PLATFORM_ROLES.filter((r) => !["PLATFORM_ADMIN", "SUPPORT", "FINANCE", "WHATSAPP_OPERATIONS", "SALES_ONBOARDING"].includes(r)).map((r) => <option key={r}>{r}</option>)}</select><input type="hidden" name="enabled" value="true"/><button className="rounded border px-3 text-sm">Save</button></form><form action={revokeUserSessionsAction}><input type="hidden" name="userId" value={user.id}/><button className="rounded border px-3 py-2 text-sm">Revoke sessions</button></form></> : <span className="text-xs font-semibold text-text-muted">Read-only access</span>}</div>)}{!admins.length && <p className="py-4 text-sm text-text-muted">No platform-admin records are persisted. Environment-email access is intentionally not editable here.</p>}</div></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Clinic users</h2><form className="mt-3 flex flex-wrap gap-2"><input name="q" defaultValue={q} placeholder="Name or email" className="h-10 rounded border px-3"/><select name="clinicId" defaultValue={clinicId || ""} className="h-10 rounded border px-3"><option value="">All clinics</option>{clinics.map((clinic) => <option key={clinic.id} value={clinic.id}>{clinic.brandName || clinic.name}</option>)}</select><button className="rounded bg-primary px-4 text-sm font-semibold text-white">Filter</button></form><div className="mt-4 divide-y">{users.map((user) => <div key={user.id} className={`grid gap-3 py-3 ${canManageClinicUsers ? "lg:grid-cols-[1fr_260px_auto]" : "lg:grid-cols-[1fr_auto]"}`}><div><p className="font-semibold">{user.fullName} · {user.role} · {user.active ? "Active" : "Disabled"}</p><p className="text-xs text-text-muted">{user.email} · {user.clinic.brandName || user.clinic.name} · last login {user.lastLoginAt?.toLocaleDateString("en-IN") || "never"}</p></div>{canManageClinicUsers ? <><form action={updateClinicUserAction} className="flex gap-2"><input type="hidden" name="userId" value={user.id}/><select name="role" defaultValue={user.role} className="h-9 rounded border px-2">{["OWNER", "ADMINISTRATOR", "DENTIST", "RECEPTIONIST", "BILLING", "ASSISTANT", "INVENTORY", "AUDITOR", "LAB"].map((r) => <option key={r}>{r}</option>)}</select><input type="hidden" name="active" value={String(user.active)}/><button className="rounded border px-3 text-sm">Save role</button></form><form action={revokeUserSessionsAction}><input type="hidden" name="userId" value={user.id}/><button className="rounded border px-3 py-2 text-sm">Revoke sessions</button></form></> : <span className="text-xs font-semibold text-text-muted">Read-only access</span>}</div>)}{!users.length && <p className="py-4 text-sm text-text-muted">No clinic users match this filter.</p>}</div></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Permission registry</h2><p className="mt-1 text-sm text-text-muted">Permissions are enforced server-side by the existing Control Center guard.</p><div className="mt-3 flex flex-wrap gap-2">{PLATFORM_PERMISSIONS.map((permission) => <span key={permission} className="rounded bg-slate-100 px-2 py-1 text-xs">{permission}</span>)}</div><p className="mt-4 text-xs text-text-muted">Secure impersonation is intentionally deferred: current sessions have no actor/target/reason/expiry impersonation context, so implementing it now would risk audit and tenant-isolation gaps.</p></section>
  </main>;
}
