import { prisma } from "@/lib/prisma";
import { requirePlatformPermission } from "@/lib/platform";

const fmt = (date: Date | null) => date ? date.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not recorded";

export default async function InfrastructurePage() {
  await requirePlatformPermission("deployment.read");
  const checkedAt = new Date(); let database = "Healthy"; let databaseDetail = "Read-only SELECT 1 completed.";
  try { await prisma.$queryRaw`SELECT 1`; } catch { database = "Down"; databaseDetail = "Read-only database health check failed."; }
  const [connections, failedOutbox, events, alerts, activeClinics] = await Promise.all([
    prisma.clinicWhatsAppConnection.count({ where: { disconnectedAt: null } }),
    prisma.scheduledWhatsAppMessage.findMany({ where: { status: { in: ["FAILED", "DEAD_LETTER"] } }, select: { id: true, status: true, attempts: true, maxAttempts: true, failureReason: true, updatedAt: true, clinic: { select: { name: true, brandName: true } } }, orderBy: { updatedAt: "desc" }, take: 50 }),
    prisma.whatsAppConnectionLog.findMany({ select: { id: true, event: true, detail: true, createdAt: true, clinic: { select: { name: true, brandName: true } } }, orderBy: { createdAt: "desc" }, take: 50 }),
    prisma.platformNotification.findMany({ where: { readAt: null }, select: { id: true, severity: true, title: true, detail: true, createdAt: true, clinicId: true }, orderBy: { createdAt: "desc" }, take: 30 }),
    prisma.clinic.count({ where: { status: "ACTIVE" } }),
  ]);
  return <main className="space-y-6 pb-12"><header><p className="text-sm font-bold uppercase tracking-[.16em] text-[#176b87]">Infrastructure</p><h1 className="mt-1 text-3xl font-bold">Technical operations</h1><p className="mt-2 text-sm text-slate-600">Read-only operational visibility. There is no arbitrary SQL, deploy, rollback, or credential control surface.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Status name="Database" value={database} detail={databaseDetail}/><Status name="WhatsApp tenant connections" value={connections ? "Healthy" : "Unknown"} detail={connections ? `${connections} active connections across ${activeClinics} active clinics.` : "No active Meta connection is recorded."}/><Status name="Message outbox" value={failedOutbox.length ? "Degraded" : "Healthy"} detail={failedOutbox.length ? `${failedOutbox.length} failed/dead-letter item(s).` : "No failed items recorded."}/><Status name="Cron & deployments" value="Unknown" detail="Cron execution and deployment history are not persisted by the current architecture."/></section>
    <section className="space-y-6"><Panel title="Failed background message jobs"><div className="divide-y">{failedOutbox.map((job) => <div key={job.id} className="py-3 text-sm"><p className="font-semibold">{job.clinic.brandName || job.clinic.name} · {job.status} · attempt {job.attempts}/{job.maxAttempts}</p><p className="text-xs text-slate-500">{job.failureReason?.slice(0, 180) || "No safe error summary"} · {fmt(job.updatedAt)}</p></div>)}{!failedOutbox.length && <Empty text="No failed or dead-letter message jobs."/>}</div></Panel><Panel title="Active platform alerts"><div className="divide-y">{alerts.map((alert) => <div key={alert.id} className="py-3 text-sm"><p className="font-semibold">{alert.severity} · {alert.title}</p><p className="text-xs text-slate-500">{alert.detail?.slice(0, 180) || "No detail"} · {fmt(alert.createdAt)}</p></div>)}{!alerts.length && <Empty text="No unread platform alerts."/>}</div></Panel></section>
    <Panel title="Meta and webhook operational events"><div className="divide-y">{events.map((event) => <div key={event.id} className="py-3 text-sm"><p className="font-semibold">{event.clinic.brandName || event.clinic.name} · {event.event}</p><p className="text-xs text-slate-500">{event.detail?.slice(0, 180) || "No safe event detail"} · {fmt(event.createdAt)}</p></div>)}{!events.length && <Empty text="No connection events have been recorded."/>}</div></Panel>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Known monitoring boundaries</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-600"><li>Cron endpoints are protected by `CRON_SECRET`, but their runs are logged to the hosting runtime rather than a database job table.</li><li>Deployment status, Vercel metadata, storage totals, database pool metrics, and external provider latency are not available without authenticated provider integrations.</li><li>Webhook payloads are not retained here; the page shows safe connection-event summaries only.</li></ul><p className="mt-4 text-xs text-slate-500">Last application-level check: {fmt(checkedAt)}</p></section>
  </main>;
}
function Status({ name, value, detail }: { name: string; value: string; detail: string }) { const good = value === "Healthy"; return <article className="rounded-xl border bg-white p-4"><p className="text-sm text-slate-500">{name}</p><p className={`mt-1 text-xl font-bold ${good ? "text-emerald-700" : value === "Degraded" || value === "Down" ? "text-rose-700" : "text-slate-700"}`}>{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">{title}</h2><div className="mt-3">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <p className="py-3 text-sm text-slate-500">{text}</p>; }
