export const dynamic = "force-dynamic";

import { CheckCircle2, Clock3, MessageCircle, RefreshCw, XCircle } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { cancelScheduledMessageAction, retryScheduledMessageAction } from "./actions";

const labels: Record<string, string> = { SCHEDULED: "Scheduled", PROCESSING: "Sending", SENT: "Sent", FAILED: "Retrying", DEAD_LETTER: "Needs attention", CANCELLED: "Cancelled", DELIVERED: "Delivered", READ: "Read", QUEUED: "Queued" };
const tone: Record<string, string> = { SCHEDULED: "bg-sky-100 text-sky-800", PROCESSING: "bg-amber-100 text-amber-800", SENT: "bg-emerald-100 text-emerald-800", FAILED: "bg-amber-100 text-amber-800", DEAD_LETTER: "bg-rose-100 text-rose-800", CANCELLED: "bg-slate-100 text-slate-700", DELIVERED: "bg-emerald-100 text-emerald-800", READ: "bg-violet-100 text-violet-800", QUEUED: "bg-slate-100 text-slate-700" };

export default async function WhatsAppOperationsPage() {
  const user = await requireUser();
  const [outbox, history] = await Promise.all([
    prisma.scheduledWhatsAppMessage.findMany({ where: { clinicId: user.clinicId }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.whatsAppMessage.findMany({ where: { conversation: { clinicId: user.clinicId }, direction: "OUTBOUND" }, include: { conversation: { select: { phone: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const pending = outbox.filter(item => ["SCHEDULED", "PROCESSING"].includes(item.status));
  const failed = outbox.filter(item => ["FAILED", "DEAD_LETTER"].includes(item.status));
  const delivered = history.filter(item => ["DELIVERED", "READ"].includes(item.deliveryStatus));
  const cards = [["Queued", pending.length, Clock3, "text-sky-700"], ["Failed", failed.length, XCircle, "text-rose-700"], ["Delivered / read", delivered.length, CheckCircle2, "text-emerald-700"], ["Outbound history", history.length, MessageCircle, "text-violet-700"]] as const;
  return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-sm font-bold uppercase tracking-[.16em] text-emerald-700">WhatsApp operations</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Message delivery centre</h1><p className="mt-2 text-muted-foreground">Monitor scheduled messages and delivery outcomes. Queue entries are retained for a complete clinic audit trail.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <article key={label} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><Icon className={`size-6 ${color}`}/></div></article>)}</section>
    <section className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-lg font-bold">Scheduled message queue</h2><p className="mt-1 text-sm text-muted-foreground">Only scheduled or failed messages can be cancelled or retried; sent records stay immutable.</p></div><div className="divide-y">{outbox.map(item => <article key={item.id} className="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.phone}</p><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${tone[item.status] || tone.QUEUED}`}>{labels[item.status] || item.status}</span><span className="text-xs text-muted-foreground">Attempt {item.attempts}/{item.maxAttempts}</span></div><p className="mt-1 truncate text-sm text-muted-foreground">{item.content}</p><p className="mt-1 text-xs text-muted-foreground">Scheduled {item.scheduledAt.toLocaleString("en-IN")}{item.failureReason ? ` · ${item.failureReason}` : ""}</p></div><div className="flex shrink-0 gap-2">{["SCHEDULED", "FAILED"].includes(item.status) && <form action={cancelScheduledMessageAction}><input type="hidden" name="id" value={item.id}/><button className="rounded-xl border border-rose-200 px-3 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-50">Cancel</button></form>}{item.status === "FAILED" && <form action={retryScheduledMessageAction}><input type="hidden" name="id" value={item.id}/><button className="inline-flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground"><RefreshCw className="size-4"/>Retry</button></form>}</div></article>)}{!outbox.length && <p className="px-6 py-12 text-center text-sm text-muted-foreground">No scheduled messages yet. Use any WhatsApp action to schedule a delivery.</p>}</div></section>
    <section className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-lg font-bold">Outbound delivery history</h2><p className="mt-1 text-sm text-muted-foreground">Provider webhooks update message status as it is sent, delivered, read, or fails.</p></div><div className="divide-y">{history.map(item => <article key={item.id} className="flex flex-col gap-2 px-6 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="font-semibold">{item.conversation.phone}</p><p className="mt-1 truncate text-sm text-muted-foreground">{item.content}</p></div><div className="flex shrink-0 items-center gap-3"><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${tone[item.deliveryStatus] || tone.QUEUED}`}>{labels[item.deliveryStatus] || item.deliveryStatus}</span><time className="text-xs text-muted-foreground">{item.createdAt.toLocaleString("en-IN")}</time></div></article>)}{!history.length && <p className="px-6 py-12 text-center text-sm text-muted-foreground">No outbound WhatsApp history yet.</p>}</div></section>
  </div>;
}
