import PageHeader from "@/components/lists/PageHeader";
import Link from "next/link";
export const dynamic = "force-dynamic";

import { CheckCircle2, Clock3, MessageCircle, RefreshCw, XCircle } from "lucide-react";
import { requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { cancelScheduledMessageAction, retryScheduledMessageAction } from "./actions";

const labels: Record<string, string> = { SCHEDULED: "Scheduled", PROCESSING: "Sending", SENT: "Sent", FAILED: "Retrying", DEAD_LETTER: "Needs attention", CANCELLED: "Cancelled", DELIVERED: "Delivered", READ: "Read", QUEUED: "Queued" };
const tone: Record<string, string> = { SCHEDULED: "bg-secondary text-primary", PROCESSING: "bg-warning-bg text-warning", SENT: "bg-success-bg text-success", FAILED: "bg-warning-bg text-warning", DEAD_LETTER: "bg-danger-bg text-danger", CANCELLED: "bg-muted text-heading", DELIVERED: "bg-success-bg text-success", READ: "bg-secondary text-primary", QUEUED: "bg-muted text-heading" };

export default async function WhatsAppOperationsPage() {
  const user = await requirePermission("sendWhatsApp");
  const [outbox, history] = await Promise.all([
    prisma.scheduledWhatsAppMessage.findMany({ where: { clinicId: user.clinicId }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.whatsAppMessage.findMany({ where: { conversation: { clinicId: user.clinicId }, direction: "OUTBOUND" }, include: { conversation: { select: { phone: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const pending = outbox.filter(item => ["SCHEDULED", "PROCESSING"].includes(item.status));
  const failed = outbox.filter(item => ["FAILED", "DEAD_LETTER"].includes(item.status));
  const delivered = history.filter(item => ["DELIVERED", "READ"].includes(item.deliveryStatus));
  const cards = [["Queued", pending.length, Clock3, "text-primary"], ["Failed", failed.length, XCircle, "text-danger"], ["Delivered / read", delivered.length, CheckCircle2, "text-success"], ["Outbound history", history.length, MessageCircle, "text-primary"]] as const;
  return <div className="flex flex-col gap-5">
    <PageHeader title="Messages" sub="Every WhatsApp thread with a patient, and everything that goes out on its own." />
    <div role="tablist" aria-label="Messages sections" className="flex gap-1 overflow-x-auto border-b border-border"><Link role="tab" aria-selected="false" href="/dashboard/conversations" className="inline-flex min-h-11 flex-none items-center border-b-2 border-b-transparent px-3.5 text-[13px] font-semibold text-text-muted hover:text-heading">Inbox</Link><Link role="tab" aria-selected="false" href="/dashboard/automation" className="inline-flex min-h-11 flex-none items-center border-b-2 border-b-transparent px-3.5 text-[13px] font-semibold text-text-muted hover:text-heading">Automations</Link><span role="tab" aria-selected="true" className="inline-flex min-h-11 flex-none items-center border-b-2 border-b-primary px-3.5 text-[13px] font-semibold text-heading">What went out</span><Link role="tab" aria-selected="false" href="/dashboard/ai-coach" className="inline-flex min-h-11 flex-none items-center border-b-2 border-b-transparent px-3.5 text-[13px] font-semibold text-text-muted hover:text-heading">Approved answers</Link><Link role="tab" aria-selected="false" href="/dashboard/settings/whatsapp" className="inline-flex min-h-11 flex-none items-center border-b-2 border-b-transparent px-3.5 text-[13px] font-semibold text-text-muted hover:text-heading">Setup</Link></div>
<header><p className="text-sm font-bold uppercase tracking-[.16em] text-success">WhatsApp operations</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Message delivery centre</h1><p className="mt-2 text-text-muted">Monitor scheduled messages and delivery outcomes. Queue entries are retained for a complete clinic audit trail.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <article key={label} className="rounded-card border bg-card p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-text-muted">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><Icon className={`size-6 ${color}`}/></div></article>)}</section>
    <section className="overflow-hidden rounded-card border bg-card shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-lg font-bold">Scheduled message queue</h2><p className="mt-1 text-sm text-text-muted">Secure links stay encrypted while queued and are removed after dispatch. Unknown outcomes require a deliberate manual retry.</p></div><div className="divide-y">{outbox.map(item => <article key={item.id} className="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.phone}</p><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${tone[item.status] || tone.QUEUED}`}>{labels[item.status] || item.status}</span><span className="text-xs text-text-muted">Attempt {item.attempts}/{item.maxAttempts}</span></div><p className="mt-1 truncate text-sm text-text-muted">{item.content}</p><p className="mt-1 text-xs text-text-muted">Scheduled {item.scheduledAt.toLocaleString("en-IN")}{item.failureReason ? ` / ${item.failureReason}` : ""}</p></div><div className="flex shrink-0 gap-2">{["SCHEDULED", "FAILED"].includes(item.status) && <form action={cancelScheduledMessageAction}><input type="hidden" name="id" value={item.id}/><button className="rounded-control border border-danger-border px-3 py-2 text-sm font-semibold text-danger hover:bg-danger-bg">Cancel</button></form>}{["FAILED", "DEAD_LETTER"].includes(item.status) && <form action={retryScheduledMessageAction}><input type="hidden" name="id" value={item.id}/><button className="inline-flex items-center gap-2 rounded-control bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground"><RefreshCw className="size-4"/>Retry after verification</button></form>}</div></article>)}{!outbox.length && <p className="px-6 py-12 text-center text-sm text-text-muted">No scheduled messages yet. Use any WhatsApp action to schedule a delivery.</p>}</div></section>
    <section className="overflow-hidden rounded-card border bg-card shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-lg font-bold">Outbound delivery history</h2><p className="mt-1 text-sm text-text-muted">Provider webhooks update message status as it is sent, delivered, read, or fails.</p></div><div className="divide-y">{history.map(item => <article key={item.id} className="flex flex-col gap-2 px-6 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="font-semibold">{item.conversation.phone}</p><p className="mt-1 truncate text-sm text-text-muted">{item.content}</p></div><div className="flex shrink-0 items-center gap-3"><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${tone[item.deliveryStatus] || tone.QUEUED}`}>{labels[item.deliveryStatus] || item.deliveryStatus}</span><time className="text-xs text-text-muted">{item.createdAt.toLocaleString("en-IN")}</time></div></article>)}{!history.length && <p className="px-6 py-12 text-center text-sm text-text-muted">No outbound WhatsApp history yet.</p>}</div></section>
  </div>;
}
