import { prisma } from "@/lib/prisma";
import { requirePlatformPermission } from "@/lib/platform";

const rangeStart = (value: string) => { const days = value === "7d" ? 7 : value === "30d" ? 30 : value === "90d" ? 90 : 1; return new Date(Date.now() - days * 24 * 60 * 60 * 1000); };
const fmt = (date: Date | null) => date ? date.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not recorded";

export default async function WhatsAppCommandCenter({ searchParams }: { searchParams: Promise<{ clinicId?: string; range?: string; direction?: string; status?: string }> }) {
  await requirePlatformPermission("whatsapp.read");
  const p = await searchParams; const clinicId = Number(p.clinicId) || undefined; const range = ["today", "7d", "30d", "90d"].includes(p.range || "") ? p.range! : "30d"; const start = rangeStart(range);
  const messageWhere = { createdAt: { gte: start }, ...(p.direction === "INBOUND" || p.direction === "OUTBOUND" ? { direction: p.direction } : {}), ...(p.status ? { deliveryStatus: p.status } : {}), ...(clinicId ? { conversation: { clinicId } } : {}) };
  const [clinics, connections, messages, conversations, templates, queue, events] = await Promise.all([
    prisma.clinic.findMany({ select: { id: true, name: true, brandName: true }, orderBy: { name: "asc" } }),
    prisma.clinicWhatsAppConnection.findMany({ where: clinicId ? { clinicId } : undefined, select: { id: true, clinicId: true, wabaId: true, phoneNumberId: true, displayPhoneNumber: true, verifiedName: true, businessName: true, qualityRating: true, messagingLimit: true, webhookVerifiedAt: true, lastSyncedAt: true, lastVerifiedAt: true, disconnectedAt: true, clinic: { select: { name: true, brandName: true } } }, orderBy: { connectedAt: "desc" } }),
    prisma.whatsAppMessage.findMany({ where: messageWhere, select: { id: true, providerMessageId: true, direction: true, messageType: true, deliveryStatus: true, failureReason: true, createdAt: true, statusUpdatedAt: true, conversation: { select: { clinicId: true, clinic: { select: { name: true, brandName: true } } } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.whatsAppConversation.findMany({ where: { ...(clinicId ? { clinicId } : {}), lastMessageAt: { gte: start } }, select: { id: true, clinicId: true, phone: true, status: true, automationMode: true, lastMessageAt: true, clinic: { select: { name: true, brandName: true } } }, orderBy: { lastMessageAt: "desc" }, take: 50 }),
    prisma.whatsAppTemplate.findMany({ where: clinicId ? { clinicId } : undefined, select: { id: true, name: true, language: true, category: true, status: true, providerId: true, updatedAt: true, clinic: { select: { name: true, brandName: true } } }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.scheduledWhatsAppMessage.findMany({ where: { ...(clinicId ? { clinicId } : {}), status: { in: ["FAILED", "DEAD_LETTER"] } }, select: { id: true, clinicId: true, status: true, attempts: true, maxAttempts: true, failureReason: true, lastAttemptAt: true, clinic: { select: { name: true, brandName: true } } }, orderBy: { updatedAt: "desc" }, take: 50 }),
    prisma.whatsAppConnectionLog.findMany({ where: clinicId ? { clinicId } : undefined, select: { id: true, event: true, detail: true, createdAt: true, clinic: { select: { name: true, brandName: true } } }, orderBy: { createdAt: "desc" }, take: 50 }),
  ]);
  const outbound = messages.filter((m) => m.direction === "OUTBOUND"); const delivered = outbound.filter((m) => ["DELIVERED", "READ"].includes(m.deliveryStatus)); const read = outbound.filter((m) => m.deliveryStatus === "READ"); const failed = outbound.filter((m) => m.deliveryStatus === "FAILED");
  const rate = (part: number, whole: number) => whole ? `${Math.round(part / whole * 100)}%` : "—";
  return <main className="space-y-6 pb-12"><header><p className="platform-eyebrow">WhatsApp</p><h1 className="mt-1 text-3xl font-bold">Automation Command Center</h1><p className="mt-2 text-sm text-muted-foreground">Tenant-scoped Meta operational metadata. Tokens, secrets, and message bodies are never selected or rendered here.</p></header>
    <form className="flex flex-wrap gap-3 rounded-xl border bg-card p-4"><select name="clinicId" defaultValue={clinicId || ""} className="h-10 rounded-lg border px-3"><option value="">All clinics</option>{clinics.map((c) => <option key={c.id} value={c.id}>{c.brandName || c.name}</option>)}</select><select name="range" defaultValue={range} className="h-10 rounded-lg border px-3"><option value="today">Today</option><option value="7d">7 days</option><option value="30d">30 days</option><option value="90d">90 days</option></select><select name="direction" defaultValue={p.direction || ""} className="h-10 rounded-lg border px-3"><option value="">All directions</option><option value="INBOUND">Inbound</option><option value="OUTBOUND">Outbound</option></select><button className="rounded-lg bg-primary px-4 text-sm font-semibold text-white">Apply</button></form>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Connected clinics" value={connections.filter((c) => !c.disconnectedAt).length}/><Metric label="Outbound / delivered" value={`${outbound.length} / ${delivered.length}`} note={`Delivery ${rate(delivered.length, outbound.length)}`}/><Metric label="Read / failed" value={`${read.length} / ${failed.length}`} note={`Read ${rate(read.length, outbound.length)}`}/><Metric label="Inbound conversations" value={conversations.length} note={`${queue.length} failed queue item(s)`}/></section>
    <Section title="Connections and phone numbers"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead><tr><th>Clinic</th><th>Phone number ID</th><th>WABA</th><th>Business</th><th>Webhook</th><th>Last sync</th></tr></thead><tbody>{connections.map((c) => <tr key={c.id}><td>{c.clinic.brandName || c.clinic.name}</td><td>{c.phoneNumberId}<br/><span className="text-xs text-text-muted">{c.displayPhoneNumber || "No display number"}</span></td><td>{c.wabaId}</td><td>{c.businessName || c.verifiedName || "Not synced"}</td><td>{c.disconnectedAt ? "Disconnected" : c.webhookVerifiedAt ? "Verified" : "Pending"}</td><td>{fmt(c.lastSyncedAt)}</td></tr>)}{!connections.length && <tr><td colSpan={6}>No tenant Meta connection is recorded.</td></tr>}</tbody></table></div></Section>
    <section className="space-y-6"><Section title="Message logs"><div className="divide-y">{messages.map((m) => <div key={m.id} className="py-3 text-sm"><p className="font-semibold">{m.conversation.clinic.brandName || m.conversation.clinic.name} · {m.direction} · {m.messageType} · {m.deliveryStatus}</p><p className="text-xs text-text-muted">Meta ID: {m.providerMessageId || "Not recorded"} · {fmt(m.createdAt)}{m.failureReason ? ` · ${m.failureReason.slice(0, 160)}` : ""}</p></div>)}{!messages.length && <Empty/>}</div></Section><Section title="Failed message queue"><div className="divide-y">{queue.map((item) => <div key={item.id} className="py-3 text-sm"><p className="font-semibold">{item.clinic.brandName || item.clinic.name} · {item.status} · {item.attempts}/{item.maxAttempts}</p><p className="text-xs text-text-muted">{item.failureReason?.slice(0, 180) || "No error summary"} · last attempt {fmt(item.lastAttemptAt)}</p></div>)}{!queue.length && <Empty text="No failed or dead-letter jobs."/>}</div></Section></section>
    <section className="space-y-6"><Section title="Templates (monitoring)"><div className="divide-y">{templates.map((t) => <div key={t.id} className="py-3 text-sm"><p className="font-semibold">{t.name} · {t.status}</p><p className="text-xs text-text-muted">{t.clinic.brandName || t.clinic.name} · {t.language} · {t.category || "Uncategorised"} · updated {fmt(t.updatedAt)}</p></div>)}{!templates.length && <Empty text="No template records are stored."/>}</div></Section><Section title="Webhook and connection diagnostics"><div className="divide-y">{events.map((e) => <div key={e.id} className="py-3 text-sm"><p className="font-semibold">{e.clinic.brandName || e.clinic.name} · {e.event}</p><p className="text-xs text-text-muted">{e.detail?.slice(0, 180) || "No safe event detail"} · {fmt(e.createdAt)}</p></div>)}{!events.length && <Empty text="No connection events are recorded."/>}</div></Section></section>
    <Section title="Conversations (privacy-minimized)"><div className="divide-y">{conversations.map((c) => <div key={c.id} className="flex justify-between gap-3 py-3 text-sm"><div><p className="font-semibold">{c.clinic.brandName || c.clinic.name} · {c.status} · {c.automationMode}</p><p className="text-xs text-text-muted">Contact ending {c.phone.slice(-4).padStart(c.phone.length, "•")}</p></div><time className="text-xs text-text-muted">{fmt(c.lastMessageAt)}</time></div>)}{!conversations.length && <Empty text="No matching conversations."/>}</div></Section>
    <p className="text-xs text-text-muted">Template creation/sync and manual retry are intentionally not exposed here: this application stores template monitoring data and only permits bounded outbox retries through the existing tenant-scoped workflow.</p>
  </main>;
}
function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) { return <article className="rounded-xl border bg-card p-4"><p className="text-sm text-text-muted">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p>{note && <p className="mt-1 text-xs text-text-muted">{note}</p>}</article>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-card p-5"><h2 className="font-bold">{title}</h2><div className="mt-3">{children}</div></section>; }
function Empty({ text = "No stored operational data matches this view." }: { text?: string }) { return <p className="py-4 text-sm text-text-muted">{text}</p>; }
